### ISSUE TITLE
CDI Integration fails with latest camel-2.17

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1026]
With 

```
    @Inject
    @ContextName("cdi-context")
    private CamelContext camelContext;
```

I see 

```
[INFO] Caused by: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"camel-tests.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"camel-tests.war\".WeldStartService: Failed to start service
[INFO]     Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type CamelContext with qualifiers @ContextName
[INFO]   at injection point [BackedAnnotatedField] @Inject @ContextName private org.wildfly.camel.archetype.test.MyServlet.camelContext
[INFO]   at org.wildfly.camel.archetype.test.MyServlet.camelContext(MyServlet.java:0)
[INFO] WELD-001475: The following beans match by type, but none have matching qualifiers:
[INFO]   - Default CDI Camel Context
[INFO] "}}
[INFO] 	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getActionResult(ServerDeploymentPlanResultFuture.java:134)
[INFO] 	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.getResultFromNode(ServerDeploymentPlanResultFuture.java:123)
[INFO] 	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.get(ServerDeploymentPlanResultFuture.java:85)
[INFO] 	at org.jboss.as.controller.client.helpers.standalone.impl.ServerDeploymentPlanResultFuture.get(ServerDeploymentPlanResultFuture.java:42)
[INFO] 	at org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper.deploy(ServerDeploymentHelper.java:55)
[INFO] 	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:77)
```

**Comment by astefanutti** [comment]
That is a consequence of [CAMEL-5742](https://issues.apache.org/jira/browse/CAMEL-5742) that has been addressed as part of the new Camel CDI component. The issue is marked as fixed since Camel `2.16.0` though that is not actually the case :).

In your case, you just have to remove the `@ContextName("cdi-context")` qualifier. The new component deploys a `CamelContext` bean with the default qualifier if no `CamelContext` beans exist (with whatever qualifier) in the application. Then, the application must _refer_ to these Camel context beans and no Camel contexts will be created automatically.

**Comment by tdiesler** [comment]
Currently we have multiple ways of wiring CamelContext in CDI. First, we use an annotated RouteBuilder and inject that into the target bean ...

**source:**

```
@ContextName("contextA")
public class RoutesContextA extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        LOG.info("Adding route from " + a + " to " + b);
        from(a).to(b);
    }
}
```

**target:**

```
public class CDIIntegrationTest {

    @Inject
    RoutesContextA routesA;
```

The second approach is we @Inject a named CamelContext

**source:**

```
@Startup
@ApplicationScoped
@ContextName("cdi-context")
public class MyRouteBuilder extends RouteBuilder {

    @Override
    public void configure() throws Exception {
    	from("direct:start").beanRef("helloBean");
    }
}
```

**target:**

```
@WebServlet(name = "HttpServiceServlet", urlPatterns = { "/*" }, loadOnStartup = 1)
public class MyServlet extends HttpServlet {
    @Inject
    @ContextName("cdi-context")
    private CamelContext camelContext;
}
```

**Comment by astefanutti** [comment]
@tdiesler, the binding of Camel contexts and associated abstractions like `RouteBuilder`, `Endpoint`, and `ProducerTemplate`, relies on CDI qualifiers.

If an application declares two {{CamelContext}} beans:
```
@ContextName("first-context")
FirstCamelContext extends DefaultCamelContext {
}

@ContextName("second-context")
SecondCamelContext extends DefaultCamelContext {
}
```
Then the resources are bound using the declared qualifiers, e.g.:
```
@ContextName("first-context")
public class FirstRouteBuilder extends RouteBuilder {
}

@ContextName("first-context")
public class SecondRouteBuilder extends RouteBuilder {
}

@Inject
@Uri("direct:inbound")
@ContextName("first-context")
ProducerTemplate firstProducer;

@Inject
@Uri("direct:inbound")
@ContextName("second-context")
ProducerTemplate secondProducer;
```
And the contexts can be injected using standard CDI type safe resolution mechanism, e.g.:
```
@Inject
@ContextName("first-context")
CamelContext firstContext;

@Inject
@ContextName("second-context")
CamelContext secondContext;
```

`@ContextName` is just a CDI qualifier that Camel CDI provides for convenience to bind resources to _named_ contexts. However, any CDI qualifiers can be used to declared Camel contexts and bind their resources and works identically than the above example.

Besides, as the multi Camel contexts application may not be the majority of use cases, Camel CDI deploys for convenience a default Camel context with the `@Default` built-in CDI qualifier if any Camel context is deployed by the application. So in your example, which is a single Camel context example, you can choose to use that default Camel context bean. Or the application can declare its own Camel context bean with whatever qualifiers that it'll use to bind the associated resources.

In a way, the new Camel CDI component restores the type safety of CDI, hence [CAMEL-5742](https://issues.apache.org/jira/browse/CAMEL-5742). Indeed, the previous version was automagically creating new Camel context instances, not even beans, for each `@ContextName` it was discovering in the deployment.

The problem for WildFly Camel is that it relies on the presence of the `@ContextName` annotation in the deployment to activate the subsystem. That logic is unfortunately not complete and should ideally be improved to cover more use cases. This relates to #925.

**Comment by tdiesler** [comment]
Done
