### ISSUE TITLE
Add support for camel-braintree

### ISSUE THREAD

**Issue by lburgazzoli** [wildfly-extras/wildfly-camel#1048]
Ref [ENTESB-4664](https://issues.jboss.org/browse/ENTESB-4664)

**Comment by tdiesler** [comment]
Blocked by camel-2.17

**Comment by tdiesler** [comment]
Done

**Comment by tdiesler** [comment]
Unfortunately, this consistently fails in Jenkins
https://fabric8-ci.fusesource.com/job/wildfly-camel-pullreq/749

I preserved the commit here
https://github.com/tdiesler/wildfly-camel/tree/wfc1048
