### ISSUE TITLE
Enable braintree integration test

### ISSUE THREAD

**Issue by lburgazzoli** [wildfly-extras/wildfly-camel#1058]
To run camel-braintree test some environment variables need to be set with Braintree supplied [api-credentials](https://articles.braintreepayments.com/control-panel/important-gateway-credentials#api-credentials):

```
    CAMEL_BRAINTREE_ENVIRONMENT=SANDBOX
    CAMEL_BRAINTREE_MERCHANT_ID=... 
    CAMEL_BRAINTREE_PUBLIC_KEY=...
    CAMEL_BRAINTREE_PRIVATE_KEY=...
```

As alternative such keys can be set in resources/braintree/braintree.properties

**Comment by jamesnetherton** [comment]
I've modified the CI jobs to (securely) inject these properties as environment variables.
