### ISSUE TITLE
Collocate classloading integration tests under one module and package 

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1097]
Not sure why we have classloading tests split between 'smoke' and 'basic'. It makes sense to unify them under the 'smoke' module.

**Comment by tdiesler** [comment]
I recently moved stuff over to basic because the core feature pack does not contain all what is being tested. Perhaps move all to basic?

**Comment by jamesnetherton** [comment]
Thanks, I'll do that.
