### ISSUE TITLE
PackageScanResolverProcessor may not unregister associated ContextCreateHandler

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1100]
I think we have a flaw in the way in which a `ContextCreateHandler` associated with a `PackageScanResolverProcessor` is [unregistered](https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/core/src/main/java/org/wildfly/extension/camel/deployment/PackageScanResolverProcessor.java#L60-L64).

DUPs are singletons. Therefore, any instance variables set during deployment processing are liable to be overwritten each time something is deployed to the container. For the `PackageScanResolverProcessor`, this is problematic because the unregistering of the `ContextCreateHandler` depends on the correct instance being available. 

This wont be the case in the following scenario:

1. Deploy Application A
2. Deploy Application B
3. Undeploy Application A
4. Undeploy Application B 

A simple test case proves this (E.g Application A tries to unregister the wrong handler):

```
(MSC service thread 1-13) APPLICATION_A.jar :: deploy() - Created ContextCreateHandler: org.wildfly.extension.camel.handler.PackageScanClassResolverAssociationHandler@20277dd6
(MSC service thread 1-5)  APPLICATION_B.jar :: deploy() - Created ContextCreateHandler: org.wildfly.extension.camel.handler.PackageScanClassResolverAssociationHandler@5c06ddae
(MSC service thread 1-11) APPLICATION_A.jar :: undeploy() - Trying to unregister ContextCreateHandler: org.wildfly.extension.camel.handler.PackageScanClassResolverAssociationHandler@5c06ddae
(MSC service thread 1-10) APPLICATION_B.jar :: undeploy() - Trying to unregister ContextCreateHandler: org.wildfly.extension.camel.handler.PackageScanClassResolverAssociationHandler@5c06ddae
```

**Comment by tdiesler** [comment]
Yes, DUPs are supposed to associate obj instances that they need to reference during undeploy with the DU.

**Comment by jamesnetherton** [comment]
So instead of an instance variable, we can add the `ContextCreateHandler` as an attachment on the DU , which can then be retrieved on undeploy?
