### ISSUE TITLE
Provide support for kie-spring  / kie-camel component

### ISSUE THREAD

**Issue by jbride** [wildfly-extras/wildfly-camel#1144]
Feature request for providing support for kie-spring and kie-camel components.
Specifically, support for execution of stateful and stateless rule sessions.
(support for cep / jbpm / human task functionality could be out of scope as many other considerations need to be taken into account).

**Comment by jamesnetherton** [comment]
I believe this is coming soon for EAP and JBoss Fuse 6.3:

https://issues.jboss.org/browse/ENTESB-5033

Not sure whether we can consume this into the WildFly-Camel community version as it's (currently) an add-on on top of the JBoss Fuse on EAP distribution. Thus built around EAP 6.

**Comment by jbride** [comment]
Sounds great.
My immediate needs are for a supported version as I'm currently using supported EAP and Fuse.
So your link to the jira helps ... thank you!

**Comment by jamesnetherton** [comment]
Going to close this. I don't think this is something we want to include with the community release. The kie stuff requires Spring 3.x and various other conflicting dependencies which would make integration very messy.

It's better as an add-on for JBoss Fuse (for now). We can revisit this in future if need be.
