### ISSUE TITLE
Upgrade Betamax to 2.0.0

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1188]
Pending fix for https://github.com/betamaxteam/betamax/issues/201

**Comment by tdiesler** [comment]
In https://github.com/wildfly-extras/wildfly-camel/blob/2.17.x/itests/standalone/extra/pom.xml we can then remove 

```
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>8.1.17.v20150415</version>
        </dependency>
```

**Comment by jamesnetherton** [comment]
My PR was merged so now bocked waiting on a new release.
