### ISSUE TITLE
WildFly-Camel patch not included with the 4.1.0 release 

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/wildfly-camel#1238]
The wildfly-patch-camel-patch-4.0.1.tar.gz file is not included within the release 4.0.1

![screenshot 2016-07-01 08 49 04](https://cloud.githubusercontent.com/assets/463790/16513926/cde5f54e-3f68-11e6-842c-8c408f109e1f.png)

**Comment by jamesnetherton** [comment]
You mean the 4.1.0 release?

Seems GitHub had some issue with the original upload so I've fixed it. The patch is available now.
