### ISSUE TITLE
Adding a jar to the classpath of Camel Context Deployments and Camel Context Definitions

### ISSUE THREAD

**Issue by mark1900** [wildfly-extras/wildfly-camel#1286]
How would I go about adding a jar to the Camel classpath so that I can use custom beans/processors etc?

For example, 
File 1: **my-processors.jar** - JAR contains the class com.company.MyProcessor

Example file: [Camel XML for Processor](https://github.com/apache/camel/blob/master/camel-core/src/test/java/org/apache/camel/builder/MyProcessor.java)
```java
public class MyProcessor implements Processor {
    private static final Logger LOG = LoggerFactory.getLogger(MyProcessor.class);
    
    public void process(Exchange exchange) {
        LOG.debug("Called with exchange: " + exchange);
    }

    @Override
    public String toString() {
        return "MyProcessor";
    }
}
```
File 2:  **my-camel-test-camel-context.xml** - Camel Context Deployment to wildfly-10.0.0.Final-camel/standalone/deployments

Example file: [Camel XML For Transform](https://github.com/apache/camel/blob/master/components/camel-spring/src/test/resources/org/apache/camel/spring/processor/transform.xml)
```java
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd
    ">

  <camelContext xmlns="http://camel.apache.org/schema/spring">
    <route>
      <from uri="timer:foo?period=10s"/>
      <process ref="myProcessor"/>
      <to uri="log:line"/>
    </route>
  </camelContext>

  <bean id="myProcessor" class="com.company.MyProcessor"/>

</beans>
```

What must be done to the JAR file **my-processors.jar**, to enable the above Camel Context Deployment **my-camel-test-camel-context.xml**?

**Comment by jamesnetherton** [comment]
You add the camel-context.xml file into the META-INF directory within the JAR. 

Then you deploy the JAR to WildFly, the Spring Camel Context will start and it should be able to find your beans / processor classes which will also be in the same JAR.

**Comment by mark1900** [comment]
What if I wanted to have a couple of generic bean/process classes that are deployed initially and add Camel Context Deployments over time?

**Comment by jamesnetherton** [comment]
You could use [JBoss Modules](https://docs.jboss.org/author/display/MODULES/Defining+a+module) for that. Then include your module dependency in your camel application JAR / WAR using a jboss-deployment-structure.xml descriptor or a manifest entry.

https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly

**Comment by mark1900** [comment]
I would have to look into this further.  Any pointers on updating the the Camel related module to include a custom jar on it's classpath?

Which is the base module for this Camel functionality?

Do I just edit the wildfly-10.0.0.Final-camel/modules/system/layers/fuse/org/apache/camel/main/module.xml to include the new custom module/jar ?

**Comment by jamesnetherton** [comment]
You could, but I'd advise against adding stuff to the camel modules. It'll make life more difficult if you want to upgrade to later versions of the camel subsystem in future (hence why they're marked as private).

Adding your own custom module and having your camel deployment depend on it is probably a better option.

**Comment by mark1900** [comment]
Any ideas on how to have my Camel deployment file (my-camel-test-camel-context.xml) depend on a module?

The [Wildfly Class Loading Section](https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly) mentions that I might be able to set up a [global modules](https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly#ClassLoadinginWildFly-GlobalModules), though I don't think this is possible with the camel subsystem.

> ```xml
<subsystem xmlns="urn:jboss:domain:ee:1.0" >            
  <global-modules>
    <module name="org.javassist" slot="main" />            
  </global-modules> 
</subsystem>
```

**Comment by tdiesler** [comment]
Option 1 is fine, Option 2 is a hack.

We also have [org.wildfly.camel.extras](https://github.com/wildfly-extras/wildfly-camel/blob/master/feature/etc/managed/wildfly/modules/system/layers/fuse/org/apache/camel/component/main/module.xml#L105) as a module extension point.

**Comment by mark1900** [comment]
Thanks for the [org.wildfly.camel.extras](https://github.com/wildfly-extras/wildfly-camel/blob/master/feature/etc/managed/wildfly/modules/system/layers/fuse/org/apache/camel/component/main/module.xml#L105) suggestion. Is my understanding correct when I created Option 3 below, or is there a better way to add a jar library to the module extension point?

Keeping in mind that I want a flexibility of Camel Context Deployments with access to a standard company jar library,  what would be the preferred option in your professional opinion?

## Option 3: 

Add the following to `<module xmlns="urn:jboss:module:1.3" name="org.apache.camel.component">`
```xml
<module name="org.apache.commons.io" slot="main" export="true" />  
```

**Summary**
module.xml - wildfly-10.0.0.Final-camel/modules/system/layers/fuse/org/apache/camel/component/main/module.xml
```xml
<module xmlns="urn:jboss:module:1.3" name="org.apache.camel.component">
    <dependencies>
        <!-- SNIPPET START -->
        <module name="org.apache.commons.io" slot="main" export="true" />  
        <!-- SNIPPET END -->
    </dependencies>
</module>

```

**Comment by tdiesler** [comment]
You probably mean 

```xml
<module xmlns="urn:jboss:module:1.3" name="org.wildfly.camel.extras">
    <dependencies>
        <module name="org.apache.commons.io" export="true" />  
    </dependencies>
</module>
```

**Comment by mark1900** [comment]
Actually, I thought the module got renamed sometime after #680 got completed, as I could not find the module with the name "org.wildfly.camel.extras" inside my wildfly-10.0.0.Final and wildfly-camel-patch-4.2.0 directories.   However, I did find this module definition at [https://github.com/wildfly-extras/wildfly-camel/blob/wildfly-10.x/feature/etc/managed/wildfly/modules/system/layers/fuse/org/wildfly/camel/extras/main/module.xml](https://github.com/wildfly-extras/wildfly-camel/blob/wildfly-10.x/feature/etc/managed/wildfly/modules/system/layers/fuse/org/wildfly/camel/extras/main/module.xml)

```bash
cd /cygdrive/C/dev/tools/wildfly-10.0.0.Final-camel
grep -r "org.wildfly.camel.extras"
modules/system/layers/fuse/org/apache/camel/component/main/module.xml:        <module name="org.wildfly.camel.extras" export="true" services="export" optional="true" />

cd /cygdrive/C/dev/tools/wildfly-camel-patch-4.2.0
grep -r "org.wildfly.camel.extras"
modules/system/layers/fuse/org/apache/camel/component/main/module.xml:        <module name="org.wildfly.camel.extras" export="true" services="export" optional="true" />
```



@tdiesler Where should this "org.wildfly.camel.extras" module live in my Wildfly 10 instance?  Do I have to manually add this module to wildfly-10.0.0.Final/modules/system/layers/fuse/org/wildfly/camel/extras/main/module.xml?

**Comment by tdiesler** [comment]
yes, like any other module that gets added to the plain vanilla wf distribution. The benefit of [this](https://github.com/wildfly-extras/wildfly-camel/blob/master/feature/etc/managed/wildfly/modules/system/layers/fuse/org/apache/camel/component/main/module.xml#L106) line is that you ONLY need to add the module and that you don't have to worry about how this gets exposed to camel aware deployments. After all, by virtue of modularity not every module one adds to the hierarchy is also visible by other modules (i.e. deployment modules)

**Comment by mark1900** [comment]
Thanks @tdiesler 

Just to recap for any one else reading this.

## Option 4 (Preferred)

Add the following to `<module xmlns="urn:jboss:module:1.3" name="org.wildfly.camel.extras">`
```xml
<module name="org.apache.commons.io" export="true" />
```

**Summary**

Create New File: module.xml (In one of the two directories given below - Not sure module location is preferred)

- wildfly-10.0.0.Final-camel/modules/system/layers/fuse/org/wildfly/camel/extras/main/module.xml
- wildfly-10.0.0.Final-camel/modules/org/wildfly/camel/extras/main/module.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="org.wildfly.camel.extras">

    <dependencies>
		<module name="org.apache.commons.io" export="true" /> 
    </dependencies>

</module>
```
