### ISSUE TITLE
Provide CI testing for camel-linkedin

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1328]
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel/lastCompletedBuild/testReport/org.wildfly.camel.test.linkedin/

**Comment by jamesnetherton** [comment]
Wont fix (for now)....

Seems there's some logic on the LinkedIn side which detects that logins are occurring from multiple locations (E.g locally and on the build environment) and subsequently denies access to the APIs. Which means we'd need to maintain multiple developer accounts in order for this to work properly.

For now I'm happy to periodically run these tests manually whenever we do major component upgrades.

I may revisit this in future. It should be possible to record and replay the API responses. There are some challenges with HTTPS in Betamax and also the alternative mock framework Hoverfly (which uses Jersey). If I can resolve these (or find an alternative) then we could go down the mock response route.
