### ISSUE TITLE
Integrate with httpclient 4.5.2 when provided by WildFly

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1357]
Cross ref: https://issues.jboss.org/browse/WFLY-7263

Also: https://issues.apache.org/jira/browse/CAMEL-10371

**Comment by jamesnetherton** [comment]
This is not resolved. We're still overriding httpclinet and httpmime.

**Comment by jamesnetherton** [comment]
Ah, my bad. it's fixed on the WF 11.x branch.

We can remove the hard coded dependency overrides on master at least.

**Comment by tdiesler** [comment]
Blocked by wildfly-11.0.0
