### ISSUE TITLE
CDI may not detect an implicit bean archive WAR

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1361]
Can be reproduced by removing [WEB-INF/beans.xml](https://github.com/wildfly-extras/wildfly-camel-examples/tree/master/camel-activemq/src/main/webapp/WEB-INF). The camel context from the annotated route builder is not created in this case.

**Comment by jamesnetherton** [comment]
This in fact seems to be a WildFly-Camel issue. For some reason, our [config file mods](https://github.com/wildfly-extras/wildfly-camel/blob/c413a5e7d98aebed19ac70502b9ac86a06704637/config/src/main/java/org/wildfly/extension/camel/config/WildFlyCamelConfigPlugin.java#L140) configure Weld with `require-bean-descriptor = true`, thus disabling implicit bean archives.

Everything works fine when this restriction is removed.
