### ISSUE TITLE
Investigate removing camel-restlet

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1383]
Integrating with camel-restlet results in some pain because none of the restlet artifacts are available in Maven central. This means anything wanting to access the restlet jars has to add a custom maven repo definition to a project pom.xml.

The WFC integration is pretty weak anyway. We currently do not allow consumers for this component (and probably never will), which leaves a simple JAX-RS restlet producer.

I think our JAX-RS story is covered well enough by:

* CXF
* Native JaveEE JAX-RS services
* Camel REST API
* Various other camel HTTP related components

**Comment by gastaldi** [comment]
+1 to remove it
