### ISSUE TITLE
Expand examples based on customer feedback

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1386]
Here's some quickstarts that some folks in consulting have put together that they try to use with customers.

https://github.com/sundarmr/eapquickstarts

CrossRef: https://github.com/wildfly-extras/wildfly-camel-examples/issues/7

- [x] #1781
- [x] #1782
- [x] #1783
- [x] #1784
- [x] #1785
- [x] #1786

**Comment by jamesnetherton** [comment]
I'll take this on....

At a minimum we should aim to replicate the existing JMS, JPA & Mail examples with Spring. I'll also pull in and tidy up some of the stuff from `sundarmr/eapquickstarts` (not everything in there is relevant or useful IMO).

We could also do with having a Spring example for the REST DSL

**Comment by jamesnetherton** [comment]
Some useful examples here too: 

https://github.com/rhtconsulting/fuse-quickstarts/tree/jboss-fuse-6.3/eap

**Comment by jamesnetherton** [comment]
- [ ] #1781
- [ ] #1782
- [ ] #1783
- [ ] #1784
- [ ] #1785
- [ ] #1786

**Comment by jamesnetherton** [comment]
Done.
