### ISSUE TITLE
Add support for component box

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1420]
http://camel.apache.org/box.html

**Comment by jamesnetherton** [comment]
Maybe best to wait for Camel 2.19 before integrating this one. The box component in 2.18.x has been deprecated and rewritten from scratch in 2.19.

**Comment by tdiesler** [comment]
Found 22 [matching posts](http://camel.465427.n5.nabble.com/template/NamlServlet.jtp?macro=search_page&node=465428&query=subject%3Abox&days=700) for subject:box in Camel - Users within 700 days Showing posts 1 to 12.
