### ISSUE TITLE
Add support for component etcd

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1427]
http://camel.apache.org/etcd.html

**Comment by jamesnetherton** [comment]
Need to implement #1702 before this can work. The etcd4j library only works with Netty 4.1.x.

**Comment by jamesnetherton** [comment]
This cannot be integrated at the moment. 

etcd4j depends on APIs in Jackson 2.8.x and WildFly 10.x is stuck on Jackson 2.7.x.

Deferring till WildFly 11 is available.
