### ISSUE TITLE
Reject support for component websocket

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1479]
http://camel.apache.org/websocket.html
https://issues.jboss.org/browse/ENTESB-6560

**Comment by jamesnetherton** [comment]
I think this component uses Jetty so we should ponder what we think good websocket integration looks like.

For WildFly, you can simply deploy a `@ServerEndpoint` annotated class from which users could inject or lookup their Camel contexts.

Another option could be to extend the camel-undertow component so that it can handle websocket URIs.

**Comment by tdiesler** [comment]
How about extending component websocket, so that it also supports undertow?

**Comment by jamesnetherton** [comment]
Yes, we could do that too.

**Comment by jamesnetherton** [comment]
Another option might be to reject support for this and instead support [camel-atmosphere-websocket](https://github.com/apache/camel/blob/master/components/camel-atmosphere-websocket/src/main/docs/atmosphere-websocket-component.adoc). This component is designed to integrate with a servlet container and does not start its own embedded server instance (E.g Jetty).

**Comment by tdiesler** [comment]
Ok, lets leave this issue open and do the atmosphere thing first

**Comment by tdiesler** [comment]
Blocked by #1406

**Comment by tdiesler** [comment]
atmosphere-websocket was rejected: #1406

**Comment by tdiesler** [comment]
All [user posts](http://camel.465427.n5.nabble.com/template/NamlServlet.jtp?macro=search_page&node=465428&query=websocket&sort=date) on first page within the four months.

**Comment by tdiesler** [comment]
We have now decided to implement this via adding websocket support to camel-undertow.

camel-websocket is heavily dependent on jetty, which leaks into public API and component parameters. For compatibility reasons, this may have to stay that way. So instead of supporting undertow in camel-websocket, we think it's better to add websocket support to camel-undertow.

In EAP websocket support is still available through camel-atmosphere-websocket or standard JavaEE Websocket Endpoints that delegate to Camel routes.

CrossRef: https://issues.apache.org/jira/browse/CAMEL-12005
