### ISSUE TITLE
Move generated docs to gh-pages branch

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1499]
With the new structure, I think we have lost the ability to publish the project documentation on a per-release basis. GitHub will be publishing from the master branch `docs` directory, which could potentially contain features that are not yet released.

We could continue to house the markdown files in `docs` but add the generated index.html to a [gh-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) branch at the end of each release (I.e as part of the release procedure). 

That way the content of `docs` can continue to evolve but the published documentation stays static till the next release.

**Comment by tdiesler** [comment]
gh-pages branch does not show up in the selection drop don any more. Maybe they removed that feature. A tagged version of the docs would be available via the wfc tag.

**Comment by jamesnetherton** [comment]
Think you need to push the branch in order for it to show up. Just tried on a test repo and it shows up in the selection dropdown afterwards.

**Comment by tdiesler** [comment]
Done

**Comment by tdiesler** [comment]
Images and sourcerefs are broken
