### ISSUE TITLE
S2I templates use hardcoded version 4.4.0

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1510]

**Comment by jamesnetherton** [comment]
Presume we're talking about the `BUILDER_VERSION` parameter here? If so, what should this default to?

IMO It can only ever be `latest` or the last WFC release tag.

Leaving it blank is not ideal because it then forces folks to manually discover what the value should be.

**Comment by tdiesler** [comment]
Ideally, this would follow ${project.version} and for SNAPSHOTS be latest - I think.

**Comment by jamesnetherton** [comment]
With the demise of the template, this is only impacts the `wildfly-camel-imagestream.json`.

Isn't this just a release process task to update the image stream tags to the new release version?

**Comment by jamesnetherton** [comment]
@tdiesler what do we want to do with this?

Automating this is tricky because having the version replaced at build time will result in a dirty workspace when we come to do releases (i.e the updated imagestream.json wont be committed with the release tag).

So either we:

* Default the image tag to `latest` so that we never have to change it (not recommended for production use cases)

Or

*  Just make it part of the release procedure to update `wildfly-camel-imagestream.json` when its copied over to the `gh-pages` branch

**Comment by jamesnetherton** [comment]
Reopening - We still have this problem in the 4.5.0 release.

**Comment by tdiesler** [comment]
It should not show up except in the changelog
```
[tdiesler@macbook wildfly-camel]$ git grep 4.4.0
README.md:$ asciidoctor -a version=4.4.0-SNAPSHOT docs/guide/index.adoc 
docs/Changelog.md:* [#1518][1518] Update s2i docs to wildfly-camel-4.4.0
docs/Changelog.md:* [#1510][1510] S2I templates use hardcoded version 4.4.0
docs/Changelog.md:#### WildFly-Camel 4.4.0
docs/Changelog.md:For details see [4.4.0 features](https://github.com/wildfly-extras/wildfly-camel/issues?q=milestone%3A"4.4.0"+label%3Afeature)
docs/Changelog.md:For details see [4.4.0 tasks](https://github.com/wildfly-extras/wildfly-camel/issues?q=milestone%3A"4.4.0"+label%3Atask)
docs/Changelog.md:For details see [4.4.0 bugs](https://github.com/wildfly-extras/wildfly-camel/issues?q=milestone%3A"4.4.0"+label%3Abug)
docs/guide/cloud/openshift-s2i.adoc:$ s2i build https://github.com/wildfly-extras/wildfly-camel-examples.git -r 4.4.0 --context-dir camel-cdi wildflyext/s2i-wildfly-camel:4.4.0 wildfly-camel-example-cdi
docs/guide/cloud/openshift-s2i.adoc:|**Git Reference**| 4.4.0
docs/guide/sources/wildfly-camel-imagestream.json:        "version": "4.4.0"
docs/guide/sources/wildfly-camel-imagestream.json:              "name": "4.4.0"
docs/guide/sources/wildfly-camel-imagestream.json:            "name": "4.4.0",
docs/guide/sources/wildfly-camel-imagestream.json:              "version": "4.4.0",
docs/guide/sources/wildfly-camel-imagestream.json:              "name": "wildflyext/s2i-wildfly-camel:4.4.0"
docs/guide/start/index.adoc:                       -DarchetypeVersion=4.4.0 \
docs/guide/start/index.adoc:                       -DarchetypeVersion=4.4.0 \
```
