### ISSUE TITLE
Document usage of wildfly-camel s2i template

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1521]
Depends on #1520

**Comment by jamesnetherton** [comment]
Lets not implement this for now (in it's current guise at least).

Maybe templates would be a better fit for some of the quickstarts. For example templates that help folks get up and running quickly with scenarios like:

* Deployment of a WFC application which interacts with ActiveMQ (or other) message broker deployed in OpenShift
* Deployment of a WFC application which interacts with a MySQL (or other) DMBS deployed in OpenShift
* Deployment of a WFC application with interacts with a Teiid / JDV installation deployed in OpenShift
* Etc...

I'm thinking along similar lines to Fuse Integration Services, where quickstarts, together with OpenShift templates give users a quick means of deploying different types of application that may want to interact with other services deployed within an OpenShift cluster.
