### ISSUE TITLE
IllegalArgumentException when trying to get CamelContext as EJB @Resource

### ISSUE THREAD

**Issue by p4w3l** [wildfly-extras/wildfly-camel#1529]
Having:

- WildFly 10.1 running with standalone.xml

- Installed wildfly-camel-plugin over existing WildFly standalone.xml configuration ( by: bin/fuseconfig.sh --configs=camel --enable )

- Camel context started with Sample-camel-context.xml as described here: https://wildflyext.gitbooks.io/wildfly-camel/content/features/context-deployments.html

- EJB @Singleton with `@Resource(name = "java:jboss/camel/context/mycontext")
    CamelContext camelContext;`

Then:

EJB @Singleton bean in **EAR EJB module** raises java.lang.IllegalArgumentException when trying to initialize camelContext

The same EJB @Singleton in **EAR WAR module** file works fine

Attached is stack trace
[trace.txt](https://github.com/wildfly-extras/wildfly-camel/files/643636/trace.txt)

**Comment by jamesnetherton** [comment]
I have not been able to reproduce this. We have some [integration tests](https://github.com/jamesnetherton/wildfly-camel/blob/1529-ejb/itests/standalone/basic/src/main/java/org/wildfly/camel/test/ejb/EjbEarIntegrationTest.java) for EJB EAR deployments. I created a simple [singleton bean](https://github.com/jamesnetherton/wildfly-camel/blob/1529-ejb/itests/standalone/basic/src/main/java/org/wildfly/camel/test/ejb/subA/HelloBean.java), into which two Spring Camel contexts are injected.

When the test runs and the `hello` method is invoked, I see the sysout messages appear in the console log.

Do you perhaps have a unit test or some example code that replicates the problem?

**Comment by p4w3l** [comment]
Hi James,
I will try to prepare an arrangement to the end of the month. I thing about EAR with small 1 WAR and 1 EJB module but without any testing environments like junit or arquillian. Do you think it will be ok ?
best regardsPaweł 

    On Wednesday, December 14, 2016 3:19 PM, James Netherton <notifications@github.com> wrote:
 

 I have not been able to reproduce this. We have some integration tests for EJB EAR deployments. I created a simple singleton bean, into which two Spring Camel contexts are injected.When the test runs and the hello method is invoked, I see the sysout messages appear in the console log.Do you perhaps have a unit test or some example code that replicates the problem?—

**Comment by jamesnetherton** [comment]
Yes, that's fine. Thanks!

**Comment by p4w3l** [comment]
Now the same EJB moved from WAR module to EJB module works fine. I am not able to reproduce the error :)

**Comment by jamesnetherton** [comment]
Thanks for retesting!
