### ISSUE TITLE
Disable camel-kafka component

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1536]
See:

https://issues.apache.org/jira/browse/CAMEL-10594

I think we should disable this component until a fix is available. Else there's the potential for threads to be left endlessly running and needlessly throwing exceptions.

**Comment by tdiesler** [comment]
We can comment this out in the component aggregation module

**Comment by jamesnetherton** [comment]
Yep - that was the plan :smiley:
