### ISSUE TITLE
Missing org.jboss.as.security dependency for module org.wildfly.extension.camel.cxf.undertow

### ISSUE THREAD

**Issue by jochenr** [wildfly-extras/wildfly-camel#1554]
Hi,

I forked the "Camel CXF JAX-WS Example" to add cxf based authentication and authorization.
First I added security to the original, spring-based example. See here:
[https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-security](https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-security)
That works fine.

Then I tried to replace the "cxfws-camel-context.xml" by a CDI Java DSL route builder ("org.wildfly.camel.examples.cxf.jaxws.JavaDSLRouteBuilder.java"). See this example:
[https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-cdi](https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-cdi)

This does not work because the LoginModule classes configured in the wildfly security domain cannot be found (more details in the README.md in the linked project).
Deactivating security (deleting JAASLoginInterceptor from the CxfEndpoint) the example works fine....

I'm not sure if this is a bug or if I didn't find the corrct module to add to "jboss-deployment-structure.xml" and/or "jboss-all.xml"....

Best regards,
Jochen

**Comment by jamesnetherton** [comment]
Hi,

Sorry that it's taken a while to respond to this.

I think the missing piece is that you need to add a module dependency to `modules/system/layers/fuse/org/wildfly/extension/camel/cxf/undertow/main/module.xml` for `org.jboss.as.security`.

Your example worked fine after I did this. There's no need for any custom dependencies in `jboss-deployment-structure.xml`.

I'll make sure this dependency is added by default for the next WildFly-Camel release.

**Comment by jamesnetherton** [comment]
By the way - did you open a Camel Jira ticket for [this](https://github.com/jochenr/wildfly-camel-examples/blob/master/camel-cxf-jaxws-cdi/src/main/java/org/wildfly/camel/examples/cxf/jaxws/JavaDSLRouteBuilder.java#L54-L67)?

**Comment by jochenr** [comment]
Hi,
thank you for patching it in the next release.
I'll add the module dependency and test it in the nexts days.

I just opened the Camel Jira ticket:[https://issues.apache.org/jira/browse/CAMEL-10708](https://issues.apache.org/jira/browse/CAMEL-10708)
