### ISSUE TITLE
Provide camel-servlet support

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#157]

**Comment by jamesnetherton** [comment]
There's a soft dependency on #199 for this.This component depends on camel-http but we have chosen to integrate camel-http4. This results in some warnings with regards to type converters:
```
WARN  [org.apache.camel.impl.converter.DefaultTypeConverter] (pool-2-thread-1) Overriding type converter from: StaticMethodTypeConverter: public static java.io.InputStream org.apache.camel.component.http4.HttpConverter.toInputStream(javax.servlet.http.HttpServletRequest,org.apache.camel.Exchange) throws java.io.IOException to: StaticMethodTypeConverter: public static java.io.InputStream org.apache.camel.component.http.HttpConverter.toInputStream(javax.servlet.http.HttpServletRequest,org.apache.camel.Exchange) throws java.io.IOException
```

Claus says that this wont cause problems (and it shouldn't as the implementation is identical across camel-http and camel-http4).

This can be mitigated once we enable control over which components are loaded and therefore what's loaded onto the classpath.

**Comment by jamesnetherton** [comment]
Closing as the module is integrated. Additional work discussed in #159 will be covered by that issue.
