### ISSUE TITLE
Upgrade to OpenShift 3.4

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1583]

**Comment by tdiesler** [comment]
'openshift/origin-all-in-one' not yet updated

```
$ vagrant box update --box openshift/origin-all-in-one
Checking for updates to 'openshift/origin-all-in-one'
Latest installed version: 1.3.0
Version constraints: > 1.3.0
Provider: virtualbox
Box 'openshift/origin-all-in-one' (v1.3.0) is running the latest version.
```

**Comment by jamesnetherton** [comment]
Hate to keep saying it, but we should forget Vagrant and move to Minishift, given that it's the preferred solution for the long term.

**Comment by tdiesler** [comment]
Yes, we can do this as soon as it becomes an official strategy advertised by [OpenShift Origin](https://www.openshift.org). We can also document the MiniShift approach as an additional option in our [Cloud Strategy](http://wildfly-extras.github.io/wildfly-camel/#_cloud_integration) section.

**Comment by jamesnetherton** [comment]
:tada: 

https://blog.openshift.com/goodbye-openshift-all-in-one-vm-hello-minishift/

https://www.openshift.org/vm/
