### ISSUE TITLE
Add GitHub topics to the project repository

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1610]
It'd be nice to add some [topics](https://github.com/blog/2309-introducing-topics) to the project so that it shows up under different search terms.

I don't have permissions to do this, hence logging an issue for it.

Some obvious initial suggestions....

* Camel
* WildFly
* WildFly-Camel
* Integration
* Java
* JavaEE

**Comment by tdiesler** [comment]
Done
