### ISSUE TITLE
hawtio could show ActiveMQ if installed

### ISSUE THREAD

**Issue by p4w3l** [wildfly-extras/wildfly-camel#1667]
Since wildfly-camel patch distributes and installs hawtio it maight activate by default ActiveMQ management-plugin when installed in Wildfly with following way: http://stackoverflow.com/questions/24921640/how-to-set-up-messaging-subsystem-using-cli-in-wildfly

**Comment by jamesnetherton** [comment]
If I understand correctly, you're asking for this https://github.com/hawtio/hawtio/issues/2185, right?

**Comment by p4w3l** [comment]
Yes

**Comment by jamesnetherton** [comment]
Ok - I think it'd be better that this is tracked in the HawtIO project under https://github.com/hawtio/hawtio/issues/2185. Once the Artemis Plugin is part of the of the HawtIO build, WildFly-Camel can consume the new functionality once it's available in a new HawtIO release.

I'll close this issue and see if I can find a resolution for https://github.com/hawtio/hawtio/issues/2185 when I have some more time.
