### ISSUE TITLE
Enable Salesforce testing in Jenkins

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1676]
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel/lastCompletedBuild/testReport/org.wildfly.camel.test.salesforce/

https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master/lastCompletedBuild/testReport/org.wildfly.camel.test.salesforce/

https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-4.x/lastCompletedBuild/testReport/org.wildfly.camel.test.salesforce/

**Comment by jamesnetherton** [comment]
Done
