### ISSUE TITLE
Enable LinkedIn testing in Jenkins

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1677]
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel/lastCompletedBuild/testReport/org.wildfly.camel.test.linkedin/

https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master/lastCompletedBuild/testReport/org.wildfly.camel.test.linkedin/

https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-4.x/lastCompletedBuild/testReport/org.wildfly.camel.test.linkedin/

Relates to #1328

**Comment by jamesnetherton** [comment]
Likely this can never work reliably across development & CI environments where requests are coming from different countries. LinkedIn will detect this and prevent logins.

I'll continue to test the LinkedIn stuff manually for now.

Leaving this unassigned in case someone else wants to have a stab at it.
