### ISSUE TITLE
Enable camel-groups to work with jgroups-4.0

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1689]
camel-2.19 upgraded to use jgroups-4.0, wich is not yet provided by wildfly

https://issues.jboss.org/browse/WFLY-8207
https://issues.jboss.org/browse/JBEAP-10580

**Comment by tdiesler** [comment]
Blocked by https://issues.jboss.org/browse/WFLY-8207

**Comment by jamesnetherton** [comment]
Out of date.
