### ISSUE TITLE
Remove explicit netty 4.1 dependency overrride

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1702]
Currently camel-2.19 already uses netty-4.1.9.Final for the camel-netty4 companent. This however does not work with camel-vertx, which is still on 4.1.8.Final

**Comment by tdiesler** [comment]
It seems that we want Camel to update its vertex component to use netty-4.1.9. If so, could you please cross ref the respective Camel issue from here?

**Comment by jamesnetherton** [comment]
I don't think there's any Camel updates required for this.

I just ran a build with Vertx linked to Netty 4.1.9 and all of the test suites passed without any problems.

The one change I did make, was to skip all of the individual Netty libraries in favour of netty-all. Vertx only avoids netty-all to keep the size of 'fat' JARs to a minimum. We have no such concerns for our distro.

**Comment by tdiesler** [comment]
Fat jars are problematic for a number of reasons.

#1 Sources often not available to IDE during debug
#2 May include arbitrary stuff that should be wired instead
