### ISSUE TITLE
Route not started when deployed in WAR sub module

### ISSUE THREAD

**Issue by sudmong** [wildfly-extras/wildfly-camel#1717]
Hello,

I am trying to a hello world using wildfly camel and following examples on following links
[Example 1](http://www.mastertheboss.com/jboss-server/wildfly-8/using-camel-with-wildfly-part-2)
[Example 2](http://blog.eisele.net/2015/07/using-camel-routes-in-java-ee-components.html)

And I am using wildfly-10.1.0.Final with wildfly-camel-patch-4.5.0. If I deploy my application as war file then it starts the camel context and route is started too. However when i deploy the same war as module in a EAR file it doesn't start the route, however context gets created, couldn't find anything wrong in war.  Can someone let me know, if I missing something or this a known bug and we have workaround or i have encountered a bug.

**Comment by jamesnetherton** [comment]
Possibly a bug. We have unit tests that cover camel EAR deployments with JAR modules but not WAR. 

So you could maybe try changing the packaging type and see if that helps.

Let me know.

**Comment by sudmong** [comment]
Thanks James for the pointer, packing a jar inside ear worked.

**Comment by jamesnetherton** [comment]
Thanks for confirming.

I'll look into the issue with the WAR deployment.

**Comment by jamesnetherton** [comment]
What's happening is that the WAR `BeanArchive` is not visible to camel-cdi, so it never discovers any  Camel routes. Hence when the Camel context is started you see:

`Total 0 routes, of which 0 are started.`

This will be fixed in next release.

**Comment by sudmong** [comment]
Thanks everyone.
