### ISSUE TITLE
Include a 'Security' section in the documentation

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#181]
Users will be curious about how to secure both 'from' and 'to' endpoints. Please provide some documentation about how this is handled.

(i.e. how to we secure an incoming Jax-WS request? How do we provide transport encryption and authentication for an outgoing Jax-WS request?)

**Comment by jamesnetherton** [comment]
Initial draft security section has been published. This documentation will evolve over time as we get a clearer picture of what endpoint security looks like.
