### ISSUE TITLE
Add support for component bonita

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1820]

**Comment by jamesnetherton** [comment]
In it's current state, we cannot integrate this component given its dependency on Jersey as the JAX-RS client.

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-11383

**Comment by jamesnetherton** [comment]
We possibly don't want to integrate the component at this time. Functionally, it is quite limited. Only one of the Bonita APIs is supported.

**Comment by tdiesler** [comment]
We don't want another BPM engine
