### ISSUE TITLE
Add support for component couchbase

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1821]

**Comment by jamesnetherton** [comment]
This component is currently not usable for running within a container. It does not shutdown the CouchBase client, hence connections are never released or it ends up endlessly attempting to reconnect to the CouchBase server.

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-11674

**Comment by oscerd** [comment]
https://github.com/apache/camel/commit/16cac67c1f9d9e7b211d92b674115ab82400bf7c

It should be fixed.

**Comment by jamesnetherton** [comment]
Yeah I noticed, many thanks for doing that so quickly :+1:
