### ISSUE TITLE
Reject support for component drill

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1823]

**Comment by jamesnetherton** [comment]
Turns out this is another JDG competitor. We've already excluded similar components.

@tdiesler Should we integrate this one on the community side or not?

**Comment by tdiesler** [comment]
This can be rejected. If there is community interest, we can always accept a PR.

**Comment by ppalaga** [comment]
@tdiesler is there anything I should do here? I see you have changed the subject, switched the labels, but the PR https://github.com/wildfly-extras/wildfly-camel/pull/2303 was closed without merging. Should I send a new PR?

**Comment by tdiesler** [comment]
Yes, sorry. I needed to do some work on issues & the catalog. This is done now.
