### ISSUE TITLE
Add support for component grpc

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1826]

**Comment by jamesnetherton** [comment]
I was hoping to squeeze this into the 4.7.0 milestone, but there's a class loading problem:

https://issues.apache.org/jira/browse/CAMEL-11343

**Comment by jamesnetherton** [comment]
Encountered another [issue](https://github.com/grpc/grpc-java/pull/3183) with Service Provider loading and usage of TCCL. 

Currently to make things work, we'd have to expose `io/grpc/internal` but our `ExportedPathTest` rules disallows this.

**Comment by jamesnetherton** [comment]
Might be best to wait for WF 11 as this now depends on yet another Netty version.
