### ISSUE TITLE
Add support for component mongodb-gridfs

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1837]

**Comment by jamesnetherton** [comment]
I wonder if we should implement this. `mongodb-gridfs` is a renaming of what was previously `gridfs` and was already [rejected](https://github.com/wildfly-extras/wildfly-camel/blob/4.6.0/catalog/src/main/resources/component.roadmap#L177) in previous releases

**Comment by tdiesler** [comment]
Reconsidering. This is supported on all other platforms.
