### ISSUE TITLE
Add support for component tika

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1850]

**Comment by ppalaga** [comment]
There is a fix in my i1850 branch https://github.com/ppalaga/wildfly-camel/commits/i1850
but it needs to wait for Camel 2.21.0 because it requires the patch for https://issues.apache.org/jira/browse/CAMEL-11976

**Comment by tdiesler** [comment]
Blocked by camel-2.21.0

**Comment by tdiesler** [comment]
This should be unblocked now

**Comment by ppalaga** [comment]
@tdiesler I do not see CAMEL-11976 in Camel 2.20.1. We indeed need to wait for  Camel 2.21.0.

**Comment by tdiesler** [comment]
Is it intentional that there is no PR for the camel-2.20.x branch and no Fix Version for 2.20.1/2?

**Comment by oscerd** [comment]
Since it is a dependency update that implies refactoring, it was merged only on master
