### ISSUE TITLE
Add support for camel connectors

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1874]
Still early days with this component, but I think it'd be useful if we support it. There's a brief explanation of it here (see item 14):

https://dzone.com/articles/apache-camel-219-released-whats-new

And some examples here:

https://github.com/apache/camel/tree/master/connectors/examples

**Comment by tdiesler** [comment]
Blocked by 2.19.4

CrossRef: https://issues.apache.org/jira/browse/CAMEL-11798
