### ISSUE TITLE
Review Spring Camel Context startup and shutdown handling

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1883]
There have been some reports of JNDI resources not being available when Spring Camel Contexts are initialised. See: 

https://issues.jboss.org/browse/ENTESB-6784
https://issues.jboss.org/browse/ENTESB-6842

It's always bugged me that we separate spring [ApplicationContext initialisation](https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/core/src/main/java/org/wildfly/extension/camel/SpringCamelContextFactory.java#L94) and the [starting](https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/core/src/main/java/org/wildfly/extension/camel/deployment/CamelContextActivationProcessor.java#L52) of the `CamelContext` across different deployment phases.

Maybe we should be doing both events together. Although `ApplicationContext.refresh();` will not start the `CamelContext`, it will initialise all aspects of the Spring application. So if the application depends on JNDI bindings (datasources, transaction managers, JMS queues etc), there's a chance that they may not be available at such an early phase in the deployment chain.

IMO, we should start the CamelContext as late as is possible (so that we have some assurance that dependencies are available) and stop the CamelContext as early as is possible (so that we shut down Camel before dependencies are stopped).

There's a similar(ish) problem documented in https://github.com/wildfly-extras/wildfly-camel/issues/1130.

**Comment by jamesnetherton** [comment]
I think we should consider this as high priority for the next release. Spring applications that make use of resources exposed by other subsystems cannot be considered reliable or stable IMO.

**Comment by jamesnetherton** [comment]
Pretty likely that the Spring JNDI issues will not allow https://github.com/wildfly-extras/wildfly-camel/pull/2061 to work with JAR deployments.

It's probably OK for WAR deployments with the `resource-ref` descriptor.

**Comment by tdiesler** [comment]
To do this properly, it'd be necessary to deploy a service that has a dependencies on known wildfly services. The camel context can start when the deployed service is up.

**Comment by jamesnetherton** [comment]
Fixed in #2239.
