### ISSUE TITLE
Expired password for Salesforce testing in Jenkins

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1901]
https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/wildfly-camel/job/wildfly-camel-4.x/lastCompletedBuild/testReport/org.wildfly.camel.test.salesforce/SalesforceIntegrationTest/testSalesforceQuery/

**Comment by jamesnetherton** [comment]
Fixed - Also updated other relevant builds.
