### ISSUE TITLE
Document usage of Camel CDI @ImportResource

### ISSUE THREAD

**Issue by jochenr** [wildfly-extras/wildfly-camel#1928]
Based on the original Apache Camel example (https://github.com/apache/camel/tree/master/examples/camel-example-cdi-xml) I implemented a wildfly-camel example that should illustrate the use of Camel XML configuration files into Camel CDI applications.

Camel XML Configuration Import support should be available since Camel 2.18.
Unfortunatley this feature doesn't seem to work.
See my example: [ https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-cdi-xml]( https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-cdi-xml)

**Comment by jamesnetherton** [comment]
I think the XML file needs to be exposed to the classpath. So placing it in `WEB-INF` may not be enough. Try adding it to `src/main/resources` so that it ends up being packaged to `WEB-INF/classes`.

**Comment by jamesnetherton** [comment]
I'll leave this issue open to serve as a reminder to add some notes to our documentation about this.

**Comment by jochenr** [comment]
Hello James,

thank you very much:-) You are right. After moving "cxfws-camel-context.xml" the example works.
I didn't expect this, because in all the other examples the *-camel-context.xml files are located in the WEB-INF folder.

If you tell me what I have to clean-up, I send you a pull request for the example (and also for my example with JAAS security). It would be nice to have some more projects in the "official examples".

Thank you
Jochen

**Comment by jamesnetherton** [comment]
Please can you clean up any unnecessary comment blocks, I see a few empty comments in some of the files.

We also need some [tests](https://github.com/jochenr/wildfly-camel-examples/tree/master/itests). Take a look at the existing ones to see how we do things. It's pretty simple, you reference the example WAR in `itests/pom.xml`, then deploy it from the Arquillian test case and verify that the example works by hitting an HTTP endpoint or checking log file content etc. 

Also, if you do submit a PR please submit it to the [wildfly-camel-examples](https://github.com/jochenr/wildfly-camel-examples) project, as I'm about to remove the examples directory from this project.

Thanks!
