### ISSUE TITLE
Module org.wildfly.extension.camel.cxf.undertow misses dependency org.picketbox

### ISSUE THREAD

**Issue by jochenr** [wildfly-extras/wildfly-camel#1945]
Hi,

I tried to write an example that uses Java-DSL and CxfEndpoints together with JAASAuthentication.
See: https://github.com/jochenr/wildfly-camel-examples/tree/master/camel-cxf-jaxws-security-cdi

To make the example work, I had to extend the module.xml of module "org.wildfly.extension.camel.cxf.undertow" by adding this line:
`<module name="org.picketbox" />`

Otherwise you get this Exception (you have to put a breakpoint in the catch block of the handleMessage(..) method of the JAASLoginInterceptor to find it):
```javax.security.auth.login.LoginException: LoginModule-Klasse kann nicht gefunden werden: org.jboss.security.auth.spi.BaseCertLoginModule from [Module "org.wildfly.extension.camel.cxf.undertow:main" from local module loader @4b53f538 (finder: local module finder @134593bf (roots: C:\daten\wildfly-camel-10.1.0.Final\modules,C:\daten\wildfly-camel-10.1.0.Final\modules\system\layers\fuse,C:\daten\wildfly-camel-10.1.0.Final\modules\system\layers\base))]```

Additionally the module "org.apache.cxf" is missing and I have to add this "jboss-deployment-structure.xml" file
```
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
  <deployment>
    <dependencies>
      <module name="org.apache.cxf" export="true" />
    </dependencies>
  </deployment>
</jboss-deployment-structure>
```

to my deployment to not get:

```
10:01:54,364 ERROR [io.undertow.request] (default task-6) UT005023: Exception handling request to /webservices/greeting-cdi: java.lang.NoClassDefFoundError: org/apache/cxf/security/transport/TLSSessionInfo
	at org.wildfly.camel.examples.cxf.jaxws.JBossCallbackHandlerTlsCert.create(JBossCallbackHandlerTlsCert.java:51)

```

I think <module name="org.apache.cxf"...> should be found out of the box when camel-cxf compoenent is used.
Or perhaps it won't be necessary after such a feature is already build in:
https://github.com/wildfly-extras/wildfly-camel/issues/1944

Best regards,
Jochen

**Comment by jamesnetherton** [comment]
Thanks for your feedback.

**Comment by jochenr** [comment]
Meanwhile I tried to migrate to version 4.8.0...
...and the issue that I have with my example changed;-(
I'll write another comment after I found out what's happening now.


P.S.: The releases page https://github.com/wildfly-extras/wildfly-camel/releases misses the download link for 4.8.0, so I took it from the maven repo...

**Comment by jochenr** [comment]
Oh, I forgot to add the "verify-client=REQUESTED" attribute in the https listener during my migration to 4.8.0
/subsystem=undertow/server=default-server/https-listener=https/:write-attribute(name=verify-client,value=REQUESTED)
With that the bug is reproducable again.

I'll update the README.md of my forked example now.

**Comment by jamesnetherton** [comment]
Thanks for the heads up on the download link for the releases page. It's fixed now (original file was corrupt).
