### ISSUE TITLE
Create a BOM for wildfly-camel

### ISSUE THREAD

**Issue by chirino** [wildfly-extras/wildfly-camel#1962]

**Comment by chirino** [comment]
Once this is in place, all quickstarts should be updated so they don't need use wildfly-camel parents.

**Comment by jamesnetherton** [comment]
This would address https://github.com/wildfly-extras/wildfly-camel-examples/issues/27.

**Comment by chirino** [comment]
This is also connected to https://issues.jboss.org/browse/ENTESB-6878

**Comment by jamesnetherton** [comment]
Probably worth using the [sundrio-maven-plugin](https://github.com/sundrio/sundrio/tree/master/maven-plugin) to generate this.

We can reference the Camel BOM to get the Camel dependencies. We should be able to do likewise and get the relevant Java EE dependencies from the WildFly / EAP parent or from one of the JBoss JavaEE BOMs.
