### ISSUE TITLE
Reject support for component atmos

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1984]

**Comment by jamesnetherton** [comment]
Does not currently work on WildFly:

https://issues.apache.org/jira/browse/CAMEL-11925

**Comment by jamesnetherton** [comment]
Regardless of the Camel issue, I think we're forced to reject this.

The problem we have is the atmos-client uses Jersey 1.x, and it does not play well when other JAX-RS providers are already present on the class path. On WF, Resteasy is always present and this clashes with Jersey.

We could try bumping the atmos libraries to Jersey 2.x but I think this would be a non-trivial task. Hence, lets reject this for now until there's some significant customer demand.

**Comment by tdiesler** [comment]
Please reject

CrossRef: https://github.com/EMCECS/atmos-client-java/issues/3
