### ISSUE TITLE
Add support for component cmis

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1989]

**Comment by jamesnetherton** [comment]
The current Apache Chemistry version used by Camel is 0.13.0, and this brings in a bunch of stuff that makes the component tricky to integrate. Bumping to 1.1.0 makes life considerably easier. Hence I raised:

https://issues.apache.org/jira/browse/CAMEL-11964

**Comment by tdiesler** [comment]
This should now be unblocked

**Comment by jamesnetherton** [comment]
Unfortunately, not. I was not allowed to have this backported to the 2.20.x branch.

I'll try and have another stab at getting this integrated with the current cmis version.
