### ISSUE TITLE
Make set of wired camel components configurable

### ISSUE THREAD

**Issue by chirino** [wildfly-extras/wildfly-camel#199]
You increase the chances that a dependency of a camel component will conflict with another 'non-camel' deployment to EAP.  As we start porting more and more of the over 100 camel components to EAP, this is likely to become an issue.

Retrofitting a selective approach to adding components to a deployment would break existing wildfly-camel apps that assumed that all components would be available to it.  So this problem needs to be thought about before sooner rather than later.

**Comment by tdiesler** [comment]
We have 2.1.0 code freeze on Mon,19-Jan - is this coming?

**Comment by tdiesler** [comment]
Deferred to 2.2.0

**Comment by tdiesler** [comment]
This needs a little more work ...

* The descriptor needs to be XML with associated schema that can be versioned and documented
* There needs to be a java data model for descriptor content
* The descriptor should be parsed in Phase.PARSE. This populates the data model
* CamelDependenciesProcessor should consume the descriptor data model

We are likely to have more deployment associated camel options in the future. The data model and the schema should be extendible. In future there may be other ways (i.e. not just from descriptor) to populate the data model.

**Comment by tdiesler** [comment]
Recommended options are 

* [JBossAllXMLElementReader](https://github.com/wildfly/wildfly-core/blob/master/server/src/main/java/org/jboss/as/server/deployment/jbossallxml/JBossAllXMLElementReader.java)
* [JBossJPAParser](https://github.com/wildfly/wildfly/blob/master/jpa/src/main/java/org/jboss/as/jpa/jbossjpaparser/JBossJPAParser.java)

**Comment by tdiesler** [comment]
Done
