### ISSUE TITLE
Add support for component grape

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2001]

**Comment by jamesnetherton** [comment]
After having a brief skim of the [documentation](http://camel.apache.org/grape.html), I wonder if we should be supporting this.

I don't think fetching and dynamically loading arbitrary camel JARs at runtime could ever work on WildFly (or in an OSGi container). Doing this in a production environment also seems dicey.

Happy to be proved wrong if there's some value to be added here.

**Comment by tdiesler** [comment]
Rejected. Grape requires using Groovy class loader with the CamelContext.
