### ISSUE TITLE
Add support for component pgevent

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2021]

**Comment by tdiesler** [comment]
Blocked by: https://issues.apache.org/jira/browse/CAMEL-11907

**Comment by jamesnetherton** [comment]
I committed some improved tests upstream. My preference would be to use Docker for this instead of Mockito. There's some integration tests to base this work on here:

https://github.com/apache/camel/tree/master/components/camel-pgevent/src/test/java/org/apache/camel/pgevent/integration

**Comment by jamesnetherton** [comment]
I was going to integrate this but there's a small class loading issue:

https://issues.apache.org/jira/browse/CAMEL-12198

We could actually get around this by exporting the PostgreSQL driver module onto the deployment classpath. Not sure if that'd be a wise move though.

**Comment by jamesnetherton** [comment]
I don't think we should export JDBC drivers onto the deployment classpath so If we are going to support this, then I suggest we only do so via a container managed `DataSource`.

There's a small snag to getting this working in WildFly, which I fixed here:

https://issues.apache.org/jira/browse/CAMEL-12272
