### ISSUE TITLE
Add support for component restlet

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2024]

**Comment by jamesnetherton** [comment]
I've been thinking for some time about how we could support restlet consumers on Undertow. Seems we have two options.....

1. Take the lazy path and tell folks that they must configure the Restlet spring servlet in their apps. Obviously this mandates the deployment of a Camel Spring application WAR. See more about this [here](https://github.com/apache/camel/blob/master/components/camel-restlet/src/main/docs/restlet-component.adoc#using-the-restlet-servlet-within-a-webapp).

2. We add our own hooks & overrides into the Camel `RestletComponent` to deploy the Restlet [ServerServlet](https://restlet.com/open-source/documentation/javadocs/2.0/jee/ext/org/restlet/ext/servlet/ServerServlet.html) onto WildFly's Undertow host.  I have a spike of this working [here](https://github.com/jamesnetherton/wildfly-camel/tree/restlet). It needs a lot of tidying, but it proves that the basic concept can work. If we think this is the best approach, then I can maybe take this issue on.

Or the third option could be to not support consumers at all.

**Comment by jamesnetherton** [comment]
To get consumers working on Undertow we need to wait for the following Camel enhancement:

https://issues.apache.org/jira/browse/CAMEL-12011
