### ISSUE TITLE
Monitor AWS object build up

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2095]
Now that we are creating AWS objects per client, it is possible that stale objects accumulate and thus incur unnecessary cost. There should be a test that fails when there are more than a given number of objects for each type.

**Comment by ppalaga** [comment]
From #wildfly-camel IRC channel:

> 09:54:36	tdiesler: ppalaga, when you have a look at the AWS tests, you'll see that they create all sorts of AWS instances. Some of them incur charges from Amazon. Its important that, that we don't get charged for stuff that is just left overs from previous (perhaps failing) tests.
> 09:55:37	ppalaga: tdiesler: makes sense.
> 09:55:39	tdiesler: ppalaga, our test suite should know what object it creates and hence fail if it sees more than expected
> 09:56:47	tdiesler: ppalaga, an @After sanity check would be ideal, but a @Before check would also be fine
