### ISSUE TITLE
Provide an example jboss-camel-context.xml

### ISSUE THREAD

**Issue by curious3** [wildfly-extras/wildfly-camel#210]
Is there an example jboss-camel-context.xml ? I can't find one in any tests either.

Can I submit the following:

    <beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
            http://activemq.apache.org/camel/schema/spring  http://activemq.apache.org/camel/schema/spring/camel-spring.xsd
            http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd 
			http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext id="camel-context-123" xmlns="http://camel.apache.org/schema/spring">
      <route>
        <from uri="direct:start" />
        <transform>
          <simple>Hello #{body}</simple>
        </transform>
      </route>
    </camelContext>
    </beans>

**Comment by tdiesler** [comment]
```
[tdiesler@macbook wildfly-camel]$ find . -name "*context.xml"
./itests/standalone/src/test/resources/camel/simple/bean-transform-camel-context.xml
./itests/standalone/src/test/resources/camel/simple/simple-transform-camel-context.xml
./itests/standalone/target/test-classes/camel/simple/bean-transform-camel-context.xml
./itests/standalone/target/test-classes/camel/simple/simple-transform-camel-context.xml
```
