### ISSUE TITLE
Provide docs for lifecycle for camel context

### ISSUE THREAD

**Issue by curious3** [wildfly-extras/wildfly-camel#211]
Can you please provide an overview diagram or some text to explain the lifecycle for the camel context. 

I see that the Camel subsystem is started by subsystem/src/main/java/org/wildfly/extension/camel/service/CamelBootstrapService.java. Does this also start any routes defined in the standalone XML? If these routes require my application code, do I package my application as a module and specify it in the route? 

Thereafter does subsystem/src/main/java/org/wildfly/extension/camel/deployment/CamelContextActivationProcessor.java start camel contexts defined in deployments? If I need to perform initialization steps before the context is started, where can I perform them?

**Comment by tdiesler** [comment]
The system camel contexts defined in standalone.xml, domain.xml can reference java types that are reachable from the camel subsystem. User defined code code must therefore exist in a module that is available at boot time (i.e. not a deployment). The camel subsystem must have a dependency on such module.

Camel context that are processed as part of a WildFly deployment are created/started as part of deploy and stopped as part of undeploy. I assume that you have the same initialisation hooks in wildfly as you have in other runtimes (e.g. Karaf) that support <spring:beans> deployments. The callbacks are handled by Camel, not WildFly.
