### ISSUE TITLE
Unable to implement Spring JMS MessageConverter

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2198]
See:

https://issues.jboss.org/browse/ENTESB-7384

You get an NCDFE if you attempt something like:

```
public class BlobMessageConverter implements MessageConverter {
...
}
```
These instances of `MessageConverter` can be configured on camel-jms endpoints, but this currently fails:
```
12:38:46,353 WARN  [org.jboss.modules] (Weld Thread Pool -- 4) Failed to define class org.wildfly.camel.examples.activemq.BlobMessageConverter in Module "deployment.example-camel-activemq.war:main" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link org/wildfly/camel/examples/activemq/BlobMessageConverter (Module "deployment.example-camel-activemq.war:main" from Service Module Loader): org/springframework/jms/support/converter/MessageConverter
```

**Comment by SourceNode** [comment]
Do you want help with this issue? If so, I can claim it.

**Comment by jamesnetherton** [comment]
@SourceNode if you want to take a look at this one, feel free. It should be simple to fix.

**Comment by jamesnetherton** [comment]
@SourceNode apologies, but there is some urgency on resolving this one, so I'm going to claim it back.
