### ISSUE TITLE
WAR deployments containing Camel libraries should be considered invalid

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2253]
Just an idea for discussion.....

We know from experience that when folks deploy 'fat' Camel WAR applications where the subsystem is activated, it can lead to all sorts of horrors.

I wonder if we should do a similar thing to the [Webservices subsystem](https://github.com/wildfly/wildfly/blob/6b61a6003f704221f66dcd9f418bcb7af88fb9ab/webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSLibraryFilterProcessor.java#L56-L78) and scan for the presence of Camel libraries in the deployment? If we find such libraries, an exception is thrown (with an appropriate explanation of why, e.g like [this](https://github.com/wildfly/wildfly/blob/4a401160bfb8ebfb9f7576c1fc6a62f2fd0210b2/webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java#L263-L265)).

I guess one drawback to implementing this, is folks who are already getting away with the 'fat' WAR approach, find their apps start failing when they upgrade the subsystem.

**Comment by tdiesler** [comment]
Yes, please! 

... and now is also the right time to do it ;-)
