### ISSUE TITLE
IBM MQ rar issue

### ISSUE THREAD

**Issue by anbeng** [wildfly-extras/wildfly-camel#2369]
Hi,

Hawtio stops working when deploying the IBM v9 MQ resource adapter (wmq.jmsra.rar) to standalone\deployments folder.

Same\similar issue to below:
https://github.com/wildfly-extras/wildfly-camel/issues/1025

Not sure if this is directly related to wildfly-camel or hawtio itself yet.

Following the steps below:
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q129260_.htm

Will update if I find anything

Update:

With the resource adapter deployed - WFLYEEMGMT0007 error in hawtio log console:

[PluginLoader] Executing task 6
[PluginLoader] Executing task 7
[Core] No connection options, connected to local JVM
[Core] No username set, checking if we have a session
[Core] Created empty user details to be filled in: { username: null, password: null }
[Core] Jolokia URL is jolokia
[Core] No connection name found, using direct connection to JVM
[Core] Operation list() failed due to: javax.management.InstanceNotFoundException : WFLYEEMGMT0007: Could not find ResourceAdapterModule
[Core] JMX tree has been loaded, data: undefined
[Core] Set update rate to: 5000
[Themes] Setting theme to Default

Not sure if below may be a similar issue that was resolved? 
https://github.com/rhuss/jolokia/issues/178

**Comment by jamesnetherton** [comment]
I wonder if you're hitting https://github.com/hawtio/hawtio/issues/2416?

HawtIO 1.5.7 will be released shortly, so maybe try upgrading to that when it's available.

**Comment by anbeng** [comment]
Ok will wait for HawtIO 1.5.7 and test. Will revert with the results.

**Comment by jamesnetherton** [comment]
FYI - 1.5.7 has been released.

**Comment by jamesnetherton** [comment]
I'm going to close this as it's really a HawtIO issue. If the problem persists with 1.5.7, feel free to open an issue with the HawtIO project.

**Comment by anbeng** [comment]
Issue resolved with 1.5.7.
