### ISSUE TITLE
Docker image does not contain hawtio

### ISSUE THREAD

**Issue by tadayosi** [wildfly-extras/wildfly-camel#2384]
Hi,

I run the docker image as follows:

    $ docker run --rm -ti -p 9990:9990 -p 8080:8080 -e WILDFLY_MANAGEMENT_USER=admin -e WILDFLY_MANAGEMENT_PASSWORD=admin wildflyext/wildfly-camel

and then trying to access to http://localhost:8080/hawtio/ I get `404 - Not Found`.

Looking into the container using `docker exec` I cannot find `hawtio.war`.

Is it expected or a bug?

**Comment by jamesnetherton** [comment]
Probably [my fault](https://github.com/wildfly-extras/wildfly-camel/blob/master/docker/s2i/assembly-artifacts.xml#L42). 

We could add it back in.

**Comment by tadayosi** [comment]
Alright. Thanks.
