### ISSUE TITLE
VersionsValidatorTest.testVersions() should list the problems rather than complaining about their number

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2385]
We should replace 
```
Assert.assertEquals("Mapping problems", 0, problems.size());
```

with something like

```
Assert.assertEquals("Mapping problems", Collections.emptyList(), problems);
```

**Comment by jamesnetherton** [comment]
I noticed this too. But the test does have:

https://github.com/wildfly-extras/wildfly-camel/blob/5d626612949aa1f06ed0365b1a60d47a977bfce6/config/src/test/java/org/wildfly/camel/test/config/VersionsValidatorTest.java#L85-L87

So you do get some indication of what went wrong.

**Comment by ppalaga** [comment]
Indeed, I got the indication, but not where I looked for it :). 

One can also run the test from IDE and in such a case, the stderr may again stay away from dev's sight.

That said, I'd still prefer to get this merged.
