### ISSUE TITLE
CXF 3.2.x requires JAX-RS 2.1

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2419]
This issue exists only in the wildfly-12.x branch that I am just rebasing on top of camel-2.21.x branch.

Camel 2.21.x requires CXF 3.2.x, whose most part is available in WildFly. The missing CXF parts are delivered by us (WFC) in `org.apache.cxf.ext`. 
Most notably, there is `org.apache.cxf:cxf-rt-frontend-jaxrs` there in `org.apache.cxf.ext` - the CXF implementation of the JAX-RS spec. 

We traditionally made `org.apache.cxf.ext` dependent on WF's `javax.ws.rs.api` which contains the JAX-RS spec jar. However, in WF12, the JAX-RS spec jar is only 2.0, while CXF's `org.apache.cxf:cxf-rt-frontend-jaxrs` 3.2.x requires 2.1.

There are two tests failing due to this: `CXFRSProducerIntegrationTest` and `TelegramIntegrationTest`.

**Comment by ppalaga** [comment]
JAX-RS 2.1 is planned for WF13 http://wildfly-development.1055759.n5.nabble.com/WildFly-12-Plans-EE8-and-Move-to-Quarterly-Iterative-Releases-td5718321.html

**Comment by ppalaga** [comment]
One way to solve this proposed by @jamesnetherton would be to temporarily disable the `cxfrs` and `telegram` components.

Alternatively, we could perhaps temporarily deliver JAX-RS spec jars ourselves.

**Comment by jamesnetherton** [comment]
Maybe we should temporarily provide the 2.1 spec in the WFC module layer. Removing camel-cxf would be a bit painful. It's a popular component and we'd have to disable a bunch of quickstart examples.

Perhaps another alternative solution would be to not depend on the WF CXF modules at all, and provide both the CXF JAX-WS & JAX-RS libraries ourselves. When the JAX-RS issue is resolved in a future WF release, we can revert things back to how they were.

**Comment by ppalaga** [comment]
Solved in WF12. The `javax.ws.rs.api` module now serves `org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:1.0.0.Final` when `ee8.preview.mode=true` property is in place.
