### ISSUE TITLE
Add a Java EE JCA-File component / support @Resource 

### ISSUE THREAD

**Issue by myfear** [wildfly-extras/wildfly-camel#244]
I thought a bit about using the file-component in Java EE and would love to see a component, which handles file access either via a JCA file-adapter or a JCR (content repository).
Thinking about something like:

  from("jca://jndiname?resource=BucketStore).to(....

On the other hand, it would also be great to just be able to inject a @Resource into a Processor like:

 @Resource(name = "jca/files")
    BucketStore bucketStore;

As for now, this does not work for me in my tests.

**Comment by tdiesler** [comment]
Is this related to camel-file #245?

**Comment by jamesnetherton** [comment]
I think we can cover JCR with camel-jcr else camel-file fulfils most requirements.
