### ISSUE TITLE
Provide camel-file support

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#245]

**Comment by myfear** [comment]
Yes, they are related. camel-file can't be used in an EE environment. So, we need another way.

**Comment by tdiesler** [comment]
... and why can this not be used (at least partially)? 

I understand that absolute path that point outside of $WILDFLY_HOME or $HOME are problematic. However stuff that is part of $wildfly.config.dir or $wildfly.data.dir should work, no?

**Comment by myfear** [comment]
The single instance most likely technically isn't an issue. It's more likely, that you run into any of or all of the following issues:

You should do everything within the Java EE container itself: you can have no certainty that you will have any consistent access to the filesystem. There are many reasons for this, the most obvious being that applications running within a container will have:
- no certainty that any subsequent invocation of an any resource would even be on the same physical server with access to the same files/filesystem (e.g. upon clustering)
- no possibility of interfering with each other (multiple applications attempting to write to the same file)
- no security issues (one app writing confidential data which another app could read)

You should also assume that you shouldn't:
- create your own threads (the container will manage this for you; if you create your own you may starve other applications in the container of CPU time)
- use socket-IO (also has security issues)
(ref: http://stackoverflow.com/questions/1789597/java-ee-programmers-do-not-write-to-files)

I personally believe, that you will have a different approach to file-handling in Java EE containers anyway. Mostly through Java Content Repository API (JSR-283/170) or even through messaging or via databases.

**Comment by tdiesler** [comment]
These may be valid reasons for the application layer. However, they should not preclude the integration of the camel-file2 component. There may well be use cases where camel-file2 works just fine. 

In future, we may decide to provide (alternative) components that address persistence in a cloud environment.
