### ISSUE TITLE
CXF + Keycloak question

### ISSUE THREAD

**Issue by anbeng** [wildfly-extras/wildfly-camel#2499]
Hi,

I am trying to configure the authentication using keycloak on a CXF rest service but the keycloak settings seem to be ignored. I suspect it may have something to do with the class below which is configuring the servlet (A vanilla jax-rs service works).

https://github.com/wildfly-extras/wildfly-camel/blob/c1519a23bbd5b5bf96806cc403ef20e28198f970/cxfhttp/src/main/java/org/apache/cxf/transport/undertow/wildfly/WildflyHTTPServerEngine.java

**standalone.xml**
`        <subsystem xmlns="urn:jboss:domain:keycloak:1.1">
			<secure-deployment name="mywebapp.war">
				<realm>myrealm</realm>
				<resource>client</resource>
				<auth-server-url>http://localhost:8180/auth</auth-server-url>
				<bearer-only>true</bearer-only>
			</secure-deployment>		
		</subsystem>
`
**also tried using keycloak.json:**

{
  "realm": "myrealm",
  "bearer-only": true,
  "auth-server-url": "http://localhost:8180/auth",
  "ssl-required": "external",
  "resource": "client",
  "confidential-port": 0
}

**camel-context.xml**:
`
    <cxf:rsServer id="cxfMyService"
                  address="/rest/MyService"
                  serviceClass="MyService">
  
  		
  		<cxf:inInterceptors>
		   <bean class="org.apache.cxf.interceptor.LoggingInInterceptor"/>
		</cxf:inInterceptors>
      	<cxf:outInterceptors>
        	<bean class="org.apache.cxf.interceptor.LoggingOutInterceptor"/>
      	</cxf:outInterceptors>
      	
		
      	<cxf:providers>
    		<ref bean="jacksonProvider"/>
    	</cxf:providers> 
    	
 		<cxf:properties>
 			<entry key="dataFormat" value="POJO"/> 
 		</cxf:properties>    	             
	</cxf:rsServer>
`
The issue seems to be the default way the servlet is created below. Is there anyway we can override or configure?

public void addServant(URL nurl, UndertowHTTPHandler handler) {

        ServletInfo servletInfo = Servlets.servlet("DefaultServlet", DefaultServlet.class)
            .addMapping("/*")
            .setAsyncSupported(true);

        DeploymentInfo servletBuilder = Servlets.deployment()
            .setClassLoader(WildflyHTTPServerEngine.class.getClassLoader())
            .setContextPath(nurl.getPath())
            .setDeploymentName("cxfdestination.war")
            .addServlets(servletInfo);

        if (nurl.getProtocol().equals("https")) {
            SecurityConstraint securityConstraint = new SecurityConstraint();
            WebResourceCollection webResourceCollection = new WebResourceCollection();
            webResourceCollection.addUrlPattern("/*");

            securityConstraint.addWebResourceCollection(webResourceCollection);
            securityConstraint.setTransportGuaranteeType(TransportGuaranteeType.CONFIDENTIAL);
            securityConstraint.setEmptyRoleSemantic(SecurityInfo.EmptyRoleSemantic.PERMIT);

            servletBuilder.addSecurityConstraint(securityConstraint);
            servletBuilder.setConfidentialPortManager(exchange -> {
                int port = exchange.getConnection().getLocalAddress(InetSocketAddress.class).getPort();
                return defaultHost.getServer().getValue().lookupSecurePort(port);
            });
        }

**Comment by ppalaga** [comment]
We are looking at a related problem with Elytron Security Domains [1]. WildFly Camel container honoring `keycloak.json` or `secure-deployment` for CXF endpoints would be a sufficient solution for your, right?

[1] https://issues.jboss.org/browse/ENTESB-7959
