### ISSUE TITLE
Provide comprehensive mail example

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#251]
Mail endpoints are primary managed endpoints. The example should show

* camel as client connects to a remote smtp endpoint
* security configuration for the camel smtp client
* how to consume a pop/imap payload directly to camel
* mail endpoint security configuration

For details that are not handled at the camel level, we need to provide pointers to the wildfly docs.

**Comment by jamesnetherton** [comment]
Documentation updated in commit https://github.com/wildfly-extras/wildfly-camel-book/commit/56f2d1e38fcfcf3af104f11dc9f89b397c518c13
