### ISSUE TITLE
Add support for camel context autoStartup=false

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2521]

**Comment by jamesnetherton** [comment]
`autoStartup` controls whether Camel will automatically start all of routes defined on the context. It's not about whether the context itself is started. See Spring test case [here](https://github.com/apache/camel/blob/3505e718db48cc0d8be5b47f6c4030c958d93a5f/components/camel-spring/src/test/java/org/apache/camel/spring/config/CamelContextAutoStartupTest.java). So in this sense this feature is already supported by WFC.

**Comment by jamesnetherton** [comment]
Having said that - there is no descriminator for WFC to determine whether a `SpringCamelContext` should be automatically started. We could use `autoStartup` for this purpose but I'm not sure if that's the right thing to do.
