### ISSUE TITLE
Use  org.hibernate.jpa.HibernatePersistenceProvider instead of org.hibernate.ejb.HibernatePersistence

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2543]
`org.hibernate.ejb.HibernatePersistence` is deprecated and will be removed in WildFly 13

**Comment by jamesnetherton** [comment]
Do you mind raising an issue and fixing this up over at wildfly-camel-examples too?

**Comment by ppalaga** [comment]
`ClassNotFoundException: org.hibernate.ejb.HibernatePersistence` will bubble up there for sure too.
