### ISSUE TITLE
Intermittent failure of YQLIntegrationTest

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2553]
YQLIntegrationTest.testBook() fails often when run together with other tests, but I saw it always passing when I run with `-Dtest=YQLIntegrationTest` only.

**Comment by jamesnetherton** [comment]
The test hits an external service which seems to be a bit flaky. Maybe we could replace it with a stubbed HTTP response.

**Comment by jamesnetherton** [comment]
This response is returned periodically:

```
<error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" yahoo:lang="en-US"><description>No definition found for Table google.books</description></error>
```

After searching around, I didn't find any clear answer for avoiding this, so I'll add some retry logic into the test cases.
