### ISSUE TITLE
LdapIntegrationTest fails with Camel 2.22.0-SNAPSHOT

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2558]
In camel-2.22.x branch and Camel e144038b7616256ff643f495165361ac6d82e2a2 LdapIntegrationTest fails

**Comment by jamesnetherton** [comment]
Working fine for me with https://github.com/apache/camel/commit/e57b788860d438e86cd924ee1dc5e6ff7d9008cd.

**Comment by ppalaga** [comment]
Maybe it is something endemic to my new laptop. Let me recheck.

**Comment by ppalaga** [comment]
Yes, works now. Since the last week, I appended ` <my-hostname> <my-hostname>.localdomain` to the localhost lines of my `/etc/hosts` and made docker accessible to my user (added to `docker` group and ch[own|mod]ed `/var/run/docker.sock`). Not sure which one helped.
