### ISSUE TITLE
Migrate to Galleon packs

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2560]
Galleon is the new provisioning mechanism of WildFly that will replace the current feature packs. Based on this http://lists.jboss.org/pipermail/wildfly-dev/2018-June/006573.html message on wildfly-dev list, we should start migrating from FPs to Galleon.

**Comment by tdiesler** [comment]
CrossRef: https://github.com/wildfly-extras/fuse-patch/issues/195

**Comment by ppalaga** [comment]
Splitting the configuration part away to https://github.com/wildfly-extras/wildfly-camel/issues/2697 because the Galleon pack part is finished, but the config part not yet.
