### ISSUE TITLE
Test Spring with an Elytron security domain

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2561]
Not to forget to do it after or together with https://github.com/wildfly-extras/wildfly-camel/issues/2464

**Comment by jamesnetherton** [comment]
Seems we have this included in the initial Elytron CXF work.

**Comment by ppalaga** [comment]
Yes, this is covered by the fix for https://github.com/wildfly-extras/wildfly-camel/issues/2595
