### ISSUE TITLE
Semicolon in if (...); { does not look right

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2562]
https://github.com/wildfly-extras/wildfly-camel/blob/e501366925a7859f8734bc5591534cf6848906bc/itests/common/src/main/java/org/wildfly/camel/test/common/utils/DMRUtils.java#L63

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/wildfly-extras/wildfly-camel/commit/3e6dd597a8ffeff7ab3daaf30a3bcbbe083b4c7d.
