### ISSUE TITLE
Add wildfly-camel module XML files to Git

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#262]
We can still have the module.xml files being generated by the Smartics Maven plugin but there are some advantages to having the files under source control:

* Maintained history of changes
* Easier to examine module references and find candidates for inclusion in other modules

**Comment by tdiesler** [comment]
Please generate to the Git location (instead of coping with ant). Currently we have CRLF issues that makes it hard to see what has actually changed

**Comment by jamesnetherton** [comment]
The Smaritcs plugin wont allow you to output module XML files to directories that already exist. If you really want to do this, you'd have to delete the existing files and directories from the source tree prior to the plugin execution (which seems a bit mad and pointless IMO).

We could modify the Smartics plugin (again) to allow this, otherwise the simplest option is to mitigate the CRLF issues with:
```
<filterchain>
  <fixcrlf/>
</filterchain>
```

**Comment by tdiesler** [comment]
yes, please create an issue with smartics (and reference it here) - this may be a feature requested by others too.

**Comment by jamesnetherton** [comment]
This needs to be smarter.....

If we removed a module, just copying everything back from target to the source tree wont work as the old module definitions will remain. This gets **very** confusing when trying to add new modules, working out deps etc.
