### ISSUE TITLE
Camel CDI default context is shared across EAR sub deployments

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2646]
As per issue title, the default context created by the CDI extension ends up being shared across all sub-deployments within an EAR:

This has some odd side effects....

Doing the following in each each sub-deployment application always results in the same Camel Context being injected
```java
public class Foo {
  @Inject
  CamelContext camelContext
} 
```

Similarly if I create `RouteBuilder` classes in every sub-deployment, they each get added to the default context. 

Not sure if that's the correct behaviour for an EAR or not. It could end up being quite confusing. @astefanutti any thoughts on this?

I know there are ways of working around this via `@ContextName` or with custom producer methods, but the default behaviour is problematic because it becomes impossible to wire the `CamelContext` to an appropriate `ClassLoader`.

**Comment by astefanutti** [comment]
It seems there is a single / global `BeanManager` instance for the EAR, which is provided to Camel CDI and other CDI archives, so any beans and injection points get globally resolved. There is a nice article about CDI in EAR that tends to confirm how WildFly behaves: https://struberg.wordpress.com/2015/02/18/cdi-in-ears/.

From the logical, programming model, standpoint, what would users expect / want? A default Camel context per WAR? Do people that structure their application into multiple WARs want to achieve isolation or modularity? For the former, it would imply having a Camel CDI extension per sub-deployment. For the later, that would be a single Camel CDI extension instance for the entire EAR.

As opposed to class loading, there is no way to work-around bean managers structure inside a CDI extension. So, if we want to achieve isolation, the only option I see would be to deploy a Camel CDI extension instance per sub-deployment.

**Comment by jamesnetherton** [comment]
Thanks for that response.

Turns out loading the extension per sub-deployment is not possible. WildFly ensures that only one extension instance is ever loaded:

https://github.com/wildfly/wildfly/blob/master/weld/common/src/main/java/org/jboss/as/weld/deployment/WeldPortableExtensions.java#L17-L26

Regardless of whether custom CDI extensions are on the class path, EAR deployments will still only ever have a single BeanManager instance. So the default CamelContext being shared across all sub-deployments seems to be the correct (for WildFly) behaviour.

I'll close this issue. But in general, it's still confusing to me why it seems valid for a CDI bean, based on a class from one WAR sub-deployment, can be injected into a bean from a different WAR sub-deployment. By default the WAR class loaders within an EAR are isolated, so inevitably such a scenario results in an NCDFE. Although there are ways around this via manifest `Class-Path` entries.

**Comment by astefanutti** [comment]
> I'll close this issue. But in general, it's still confusing to me why it seems valid for a CDI bean, based on a class from one WAR sub-deployment, can be injected into a bean from a different WAR sub-deployment. By default the WAR class loaders within an EAR are isolated, so inevitably such a scenario results in an NCDFE. Although there are ways around this via manifest Class-Path entries.

I agree. In our use case, that is from a CDI extension standpoint, it's a bit different as the Camel CDI extension uses the Camel classes and discover beans of these types.
