### ISSUE TITLE
Camel CXF consumer deployments result in memory leaks

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2649]
Seems that deployments utilising CXF consumers result in memory leaks. This is pretty bad because the CamelContext retains links to the deployment ClassLoader and lots of other stuff.

To see this, run CXFWSConsumerIntegrationTest multiple times, then perform a heap dump and look for CamelContext instances.

Here's an example heap dump where I ran the test 10 times:

![camel-context-heap-dump](https://user-images.githubusercontent.com/4721408/45747429-bd309d80-bbfd-11e8-8110-939f2df9913e.png)

Likely this has been an issue for some time. I tested on the 7.0.0 release with WF 13 and the issue is present (so we can't blame the CXF Elytron integration :wink:) .

**Comment by ppalaga** [comment]
In WildFly Camel, there are two more independent causes for the leak. Let's track them separately:

1: https://github.com/wildfly-extras/wildfly-camel/issues/2655

**Comment by ppalaga** [comment]
Dissolved into https://issues.apache.org/jira/browse/CAMEL-12829 #2655 and #2656
