### ISSUE TITLE
Observability support

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2719]
Paraphrasing @pilhuhn 's message:

* Our users want and need to observe their running apps - on Kubernetes/OpenShift, bare metal or in classical virtual environments
* Tools like Kiali want to show (service mesh) health by also including application health
* MicroService architectures need different tooling, e.g. attaching a profiler to a monolith will no longer really work with many small distributed services

Thinks we should support:

1. Export metrics in Prometheus format

2. Export logs in a Json format that ECL(Enterprise Commons Logging (group)) can consume

3. Make health check endpoints available

4. Enable Distributed Tracing - our opinionated tracer client is the Jaeger one

5. Allow for identification of the runtime within container images (e.g. label them with a product identifier)

**Comment by jamesnetherton** [comment]
I think we have most of this covered.....

WF already provides support for health, metrics & tracing.

We get additional tracing capabilities from the Camel tracing components and there's also a microprofile metrics component coming in Camel 3.x, which we can use to leverage the container manged `MetricRegistry`.

The only part I see that's missing, is to have some health check(s) for each deployed `CamelContext`.

**Comment by jamesnetherton** [comment]
I think we have all of the relevant parts for this story now.
