### ISSUE TITLE
Module org.dozer.mapper cannot find javax.el implementation

### ISSUE THREAD

**Issue by Not-Code** [wildfly-extras/wildfly-camel#2720]
During the camel-dozer component startup 2 warnings are printed in the log:

> 2018-12-05T22:42:44.076Z WARN [org.dozer.el.ELExpressionFactory] (MSC service thread 1-7) > javax.el is not supported; Failed to resolve ExpressionFactory, com.sun.el.ExpressionFactoryImpl from [Module "org.dozer.mapper" version 6.2.0 from local module loader @37e547da (finder: local module finder @2b6856dd (roots: /wildfly/provided_modules,/wildfly/modules,/wildfly/modules/system/layers/fuse,/wildfly/modules/system/layers/base))]
> 2018-12-05T22:42:44.076Z WARN [org.apache.camel.converter.dozer.MapperFactory] (MSC service thread 1-7) > Expressions are not supported by Dozer. Are you missing javax.el dependency?

The missing dependency is forcing dozer to use the NoopELEngine. Adding the **org.glassfish.javax.el** dependency directly to the module.xml is resolving the issue:

```
<?xml version="1.0" encoding="UTF-8"?>
<module name="org.dozer.mapper" xmlns="urn:jboss:module:1.1">
    <properties>
        <property name="jboss.api" value="private"/>
    </properties>
    <resources>
        <resource-root path="dozer-core-6.2.0.jar"/>
    </resources>
    <dependencies>
        <module name="javax.api"/>
        <module name="javax.el.api"/>
        <module name="org.glassfish.javax.el"/>
        <module name="javax.xml.bind.api"/>
        <module name="org.apache.camel.component.dozer"/>
        <module name="org.apache.commons.beanutils"/>
        <module name="org.apache.commons.io"/>
        <module name="org.apache.commons.lang3"/>
        <module name="org.objenesis"/>
        <module name="org.slf4j"/>
    </dependencies>
</module>
```

**Comment by tdiesler** [comment]
This is likely out of date. In the current master, we have [this|https://github.com/wildfly-extras/wildfly-camel/blob/master/feature/modules/src/main/resources/modules/system/layers/fuse/com/github/dozermapper/main/module.xml] dozer module. Note, it is using com.github.dozermapper. In the Camel dependency tree, there is no org.glassfish.javax.el

Perhaps you can reproduce what you are seeing, by modifying this [test case|https://github.com/wildfly-extras/wildfly-camel/tree/master/itests/standalone/basic/src/test/java/org/wildfly/camel/test/dozer].

**Comment by jamesnetherton** [comment]
IIRC the Glassfish dependency is defined as both `optional` and scoped as `provided`. Hence we don't include it in our distro by default:

https://github.com/DozerMapper/dozer/blob/6.4.1/core/pom.xml#L101-L106

Also, the camel-dozer Karaf feature is including the glassfish javax.el:

https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml#L554

**Comment by jamesnetherton** [comment]
It's also in the component POM, so maybe we're excluding it somewhere:

https://github.com/apache/camel/blob/camel-2.23.0/components/camel-dozer/pom.xml#L57-L61
