### ISSUE TITLE
MALWARE in maven repository stored dependency file during build

### ISSUE THREAD

**Issue by korimo** [wildfly-extras/wildfly-camel#2729]
I cloned the project and tried to build it yesterday 19.dec 2018 evening ZULU.
It failed at
wildfly-camel/feature/pack/pom.xml
mvn install

on failed download of dependend file
&lt;dependency&gt;
            &lt;groupId&gt;org.acplt.remotetea&lt;/groupId&gt;
            &lt;artifactId&gt;remotetea-oncrpc&lt;/artifactId&gt;
            &lt;version&gt;1.1.2&lt;/version&gt;
        &lt;/dependency&gt;

our router blocked the file
remotetea-oncrpc-1.1.2.jar

with this messaGE:
<*- Network Based Malware
From "asa5508sfr" at Wed Dec 19 18:42:28 2018 UTC -*>  
Sha256: 5db61815b406f964a691ef5b3c7fae6107d45713c4c32bbbaa1268e5a0624d12
Disposition: Malware
Threat name: W32.Auto:5db61815b4.in05.Talos

**Comment by ppalaga** [comment]
Thanks for the report, @korimo, we are investigating.

**Comment by zregvart** [comment]
Nothing detected by VirusTotal:

https://www.virustotal.com/#/file/5db61815b406f964a691ef5b3c7fae6107d45713c4c32bbbaa1268e5a0624d12/detection

False positive?

**Comment by ppalaga** [comment]
This is most probably a false alarm. According to Cisco TALOS threat name classification [1] `W32.Auto:5db61815b4.in05.Talos` falls under the `/^.*in05.Talos/` group characterized by 

> Conviction of a file that is attached to a known Spam or Phishing Campaign. May not necessarily be malicious

[1] https://www.talosintelligence.com/amp-naming

**Comment by korimo** [comment]
Idk it was Cisco router whi blocked the download.

Dňa št 20. 12. 2018, 12:05 Zoran Regvart <notifications@github.com>
napísal(a):

**Comment by tdiesler** [comment]
Blocked by a response from the prod sec people

**Comment by ppalaga** [comment]
Classified as false positive by Red Hat Product Security
