### ISSUE TITLE
Invalid TCCL for CXF webapp deployments

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2782]
A user reports ...

```
	ClassLoader cl = Thread.currentThread().getContextClassLoader();
    if(cl instanceof ModuleClassLoader) {
      ModuleClassLoader mcl = (ModuleClassLoader)cl;
      String moduleName = mcl.getModule().getIdentifier().toString();
      if(moduleName.startsWith("deployment")) {
```

The problem is that the "moduleName" for Camel applications (at least for Camel-CXF based applications) is always "org.wildfly.extension.camel.cxf.undertow" instead of "deployment.OurApplication.war".

CrossRef: https://issues.jboss.org/browse/ENTESB-10373

**Comment by RickJWagner** [comment]
The attached file highlights the issue.  It is a lightly re-worked version of the CXF quickstart.

Output from sysouts in a Camel processor and a CXF interceptor:

15:56:31,041 INFO  [stdout] (default task-5) ### process gets moduleNameorg.wildfly.extension.camel.cxf.undertow                                                                                      

15:56:31,075 INFO  [stdout] (default-workqueue-1) ### handleMessage gets moduleNamedeployment.example-camel-cxf-jaxws-cdi-xml.war  

It's desirable to have the Camel Processor also able to access the name of it's deployment.

/home/rick/Tools/A/Fuse7/Fuse7_GA/jboss-eap-7.1.0/jboss-eap-7.1/quickstarts/camel/A_camel-cxf-4interceptor.tar.gz

**Comment by RickJWagner** [comment]
[A_camel-cxf-4interceptor.tar.gz](https://github.com/wildfly-extras/wildfly-camel/files/3020133/A_camel-cxf-4interceptor.tar.gz)

**Comment by jamesnetherton** [comment]
I'm pretty sure this got fixed during refactoring for Elytron compatibility on Camel CXF consumers.

The old code set the wrong ClassLoader on the dynamic CXF endpoint deployment:

https://github.com/wildfly-extras/wildfly-camel/blob/7.0.0/cxfhttp/src/main/java/org/apache/cxf/transport/undertow/wildfly/WildflyHTTPServerEngine.java#L65

The updated code correctly sets the ClassLoader to that of the parent deployment:

https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/core/src/main/java/org/wildfly/extension/camel/service/CamelEndpointDeployerService.java#L136

For Fuse, this change first went into 7.1, so it'll likely be fixed in that release onwards.

**Comment by RickJWagner** [comment]
Enlosing another small application to show the *desired* behavior.  (Contrast this with the behavior we see with Wildfly/Camel, where we do not get the proper module/deployment name.)

This is a plain JEE (not Wildfly/Camel) CXF application.  It's purpose is to demonstrate that JEE applications get correct and consistent reporting of module name from the current thread's ContextClassLoader.

Build and deploy the application, then view module name reported from:

(Servlet) at http://localhost:8080/PlainCXF_ClassLoader_Reporter/SimpleServlet
(CXF) at http://localhost:8080/PlainCXF_ClassLoader_Reporter/Greeter?wsdl

14:13:36,478 INFO  [stdout] (default task-19) ### CXF gets moduleNamedeployment.PlainCXF_ClassLoader_Reporter.war
14:13:57,573 INFO  [stdout] (default task-20) ### Servlet gets moduleNamedeployment.PlainCXF_ClassLoader_Reporter.war


[PlainCXF_ClassLoader_Reporter.tar.gz](https://github.com/wildfly-extras/wildfly-camel/files/3040421/PlainCXF_ClassLoader_Reporter.tar.gz)

**Comment by tdiesler** [comment]
With the second attachment on the [latest EAP based wfc build](https://github.com/jboss-fuse/wildfly-camel), I see 

```
10:03:38,980 INFO  [stdout] (default task-1) ### Servlet gets moduleNamedeployment.cxf.classloader.reporter-0.0.1-SNAPSHOT.war
```

which is correct.

**Comment by tdiesler** [comment]
With the first attachment, I see

```
10:14:58,966 INFO  [org.wildfly.extension.camel] (ServerService Thread Pool -- 109) Add Camel endpoint: http://127.0.0.1:8080/example-camel-cxf-jaxws-cdi-xml
10:14:58,979 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0010: Deployed "example-camel-cxf-jaxws-cdi-xml.war" (runtime-name : "example-camel-cxf-jaxws-cdi-xml.war")
10:15:56,624 INFO  [stdout] (default task-2) ### process gets moduleNamedeployment.example-camel-cxf-jaxws-cdi-xml.war
10:15:56,624 INFO  [org.wildfly.camel.examples.cxf.jaxws.GreetingsProcessor] (default task-2) process runs!
10:15:56,648 INFO  [stdout] (default-workqueue-1) Handle Message in MyInterceptor
10:15:56,649 INFO  [stdout] (default-workqueue-1) ### handleMessage gets moduleNamedeployment.example-camel-cxf-jaxws-cdi-xml.war
10:15:56,650 INFO  [stdout] (default-workqueue-1) MyProperties null
10:15:56,651 INFO  [stdout] (default-workqueue-1) MyInterceptor exits
```

which also is correct.
