### ISSUE TITLE
Enable Camel subsystem based on annotated types

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2872]
Now that @ContextName is no longer available as a descriminator, we may want to detect Camel deployments on annotated types that implement CamelContext

**Comment by jamesnetherton** [comment]
We should also consider impls of `RouteBuilder` (maybe even any `org.apache.camel.*` type) in the annotated types we check for.

At a minimum we should look for types annotated with `@Named`, `@Produces`, `@ApplicationScoped` and maybe `@Inject`.
