### ISSUE TITLE
Failing to build 9.1.0

### ISSUE THREAD

**Issue by jarek-przygodzki** [wildfly-extras/wildfly-camel#2921]
Building version 9.1.0 from source fails with error

```
git checkout 9.1.0
mvn clean install

[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:3.0.0.CR1:provision (server-provisioning) on project wildfly-camel-config: Failed to provision the state: Failed to read galleon/universe/producer/locations/wildfly-servlet/maven-producer.xml: ParseError at [row,col]:[7,12]
[ERROR] Message: Failed to instantiate producer wildfly-servlet: Failed to parse galleon/universe/producer/wildfly-servlet/maven-producer.xml: ParseError at [row,col]:[6,22]
[ERROR] Message: unexpected content: element start{urn:jboss:galleon:maven:producer:1.0}default-channelnull
```

Ability to compile older versions is important, given that WildFly 15.0.1.Final is not that old. 
 **Whats the proper procedure for applying fixes to older versions?**

## I've tried the following

Changing version of _org.jboss.galleon:galleon-maven-plugin_ to _3.0.1.Final-4.0.3.Final_ changes nothing, _4.0.4.Final_ fails with diffrent error 

```
[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.0.4.Final:provision (server-provisioning) on project wildfly-camel-config: Execution server-provisioning of goal org.jboss.galleon:galleon-maven-plugin:4.0.4.Final:provision failed.: ProviderMismatchException
```

`java.nio.file.ProviderMismatchException` happens because _WfInstallPlugin_ compares paths that are on diffrent filesystems, one of them is ZipFileSystem. It was fixed in [WFGP-122](https://github.com/wildfly/galleon-plugins/pull/107)  but wildfly-galleon-plugins.jar embedded in wildfly-core-galleon-pack-7.0.0.Final is in version 3.0.0.Final.

What I'd like to be able to rely on is all releases of _WildFly Camel Subsystem_  building after they were released, which is sadly not the case here.

**Comment by jamesnetherton** [comment]
I can't think of any simple way to resolve this. The Galleon plugin seems to be fundamentally [broken](https://developer.jboss.org/thread/280609) in all releases before 4.0.4.Final and I don't think it's possible to adjust the dependencies that the Galleon packs are tied to. 

We don't really have a formal policy of patching older releases. We usually 'fix forward' and expect folks to move on to the next WildFly / Camel releases that the subsystem supports.

All of the releases from 10.0.0 onwards build fine with `galleon-maven-plugin` 4.0.4.Final. It's unfortunate that 9.1.0 remains in its broken state.

**Comment by jarek-przygodzki** [comment]
That's what I was afraid of. Unfortunately, I can't upgrade from WildFly 15 right now. I'm willing to do the maintenance work on 9.1, but the fact that I can't even build that thing is kind of jarring.

Do you think that the Galleon issue can be fixed in WidFly 15.0.x fork?

**Comment by jamesnetherton** [comment]
Yes, I was thinking that you could possibly fix it by forking WildFly / WildFly Core to tweak the Galleon version and rebuild `wildfly-core-galleon-pack`.

**Comment by tdiesler** [comment]
@jarek-przygodzki I agree this is a bad situation. Pls complain loudly on the WildFly channel. Oleksiy Lubyanskyy who leads the Galleon effort is very helpful. Once the fix is provided there we can also fix it here.

**Comment by jarek-przygodzki** [comment]
> Yes, I was thinking that you could possibly fix it by forking WildFly / WildFly Core to tweak the Galleon version and rebuild `wildfly-core-galleon-pack`.
That's feasible, since we already use a fork of 15.0.x. How would I go about doing this?

**Comment by jamesnetherton** [comment]
> How would I go about doing this?

Something like this (I think)...

1. Branch wildfly-core from the 7.0.0.Final tag, update the Galleon versions in pom.xml to 4.0.4.Final and build the project

2. Modify WildFly pom.xml to incorporate the new wildfly-core build. Also update the Galleon version properties.

3. Branch WildFly-Camel from the 9.1.0 tag and update the WildFly version property to point at your new WildFly build. Also update update the Galleon version properties (there are 2). `version-wildfly-galleon-plugin` will likely need to be something like 3.0.1.Final

It might work, I've not tried it. Obviously the ideal solution would be for the WildFly team to resolve this problem.

**Comment by jarek-przygodzki** [comment]
> It might work, I've not tried it. Obviously the ideal solution would be for the WildFly team to resolve this problem.

I will give it a try and let you know if it worked. Unfortunately, I'm afraid that chances of another official release from 15.0.x branch are pretty slim.

**Comment by jarek-przygodzki** [comment]
It worked, eventually.  I run [this script](https://gist.github.com/jarek-przygodzki/334ab904aa9a1e23595a64f1c371ca99) and first attempt failed with silly error because of [GERONIMO-6590](https://issues.apache.org/jira/browse/GERONIMO-6590): turns out `org.apache.activemq:activemq-spring:jar:5.15.7` brings dependency to artifact with damaged POM. How was that not an issue when 9.1 was released?

```
[ERROR] Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:4.0.4.Final:build-feature-pack (feature-pack-build) on project wildfly-camel-feature-modules: Exception while reading model for org.apache.geronimo.specs:specs:pom:1.1. Resolved pom file c:\m2\repository\org\apache\geronimo\specs\specs\1.1\specs-1.1.pom: Failed to parse artifact POM model: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...</developers>\n    `\n    <p... @91:7) -> [Help 1]
[ERROR]
```
After fixing that, the build seems to succeed (didn't run full test suite).

**Comment by jamesnetherton** [comment]
Likely something changed between the 3.x version and 4.x of `wildfly-galleon-maven-plugin` (maybe it swallowed such errors?), so it was never an issue for the original 9.1 release.

**Comment by jarek-przygodzki** [comment]
I consider this resolved, so closing.
