### ISSUE TITLE
Add support for Camel-2.x on WildFly-18

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2962]
```
wildfly-18.0.1 => cxf-3.3.3
camel-2.24.2 => cxf-3.2.10
camel-2.24.3 => cxf-3.2.11
camel-2.25.0 => cxf-3.3.5
```

**Comment by tdiesler** [comment]
https://ci.fabric8.io/view/wildfly-camel/job/wildfly-camel-2.x/

**Comment by tdiesler** [comment]
Done

**Comment by mareknovotny** [comment]
@tdiesler do you have any time estimation when a final version will be released with this change?

**Comment by tdiesler** [comment]
Sure, every milestone has a release date 
https://github.com/wildfly-extras/wildfly-camel/milestone/37

**Comment by mareknovotny** [comment]
great. so april fool time
