### ISSUE TITLE
Can not build 11.0.1

### ISSUE THREAD

**Issue by akreienbring** [wildfly-extras/wildfly-camel#2963]
Hello,
as the patch for this version is not available on the releases site I downloaded the source.zip.

`mvn clean install ` took 27 min. with maven 3.6.3 and showed some error.

And searching the target directories I could not identify the 

- domain
- standalone
- modules

folders you deliver as "The Patch"

Any advice for a poor newbie? :-)

![maven_error](https://user-images.githubusercontent.com/9348725/82736015-ab829000-9d26-11ea-817d-dd0aabf8588d.jpg)

**Comment by jamesnetherton** [comment]
The patch is available in maven central here:

https://repo1.maven.org/maven2/org/wildfly/camel/wildfly-camel-patch/11.0.1/wildfly-camel-patch-11.0.1.tar.gz

**Comment by akreienbring** [comment]
Thanks!
