### ISSUE TITLE
Caused by: java.util.ServiceConfigurationError: org.jboss.as.cli.CommandHandlerProvider:

### ISSUE THREAD

**Issue by Sindhuja1295** [wildfly-extras/wildfly-camel#2971]
Dear Team,

Kindly check the below error,

Provider org.wildfly.extension.messaging.activemq.jms.cli.ConnectionFactoryHandlerProvider not a subtype

Below is my code, As need to restart the widlfly server.

 public static void reStartServer() {

        try {

            CommandContext ctx = CommandContextFactory.getInstance().newCommandContext("jmsuser","P@ssw0rd".toCharArray());
            ctx.connectController("localhost", 9990);
            ModelNode cliCommand = null;
            try {
                String request1 = "reload";
                System.out.println("ctx>>>>>>>>>>>>" + ctx.buildRequest(request1));
                cliCommand = ctx.buildRequest(request1);
                String output = executeCommand(ctx, cliCommand);

                System.out.println("output>>>>>>>>>>>>> " + output);
            } catch (CommandFormatException e) {
                e.printStackTrace();
            }

            ctx.disconnectController();
            ctx.terminateSession();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static String executeCommand(CommandContext ctx, ModelNode modelNode) {

        ModelControllerClient client = ctx.getModelControllerClient();
        if (client != null) {
            try {
                ModelNode response = client.execute(modelNode);
                System.out.println(response);
                return (response.toJSONString(true));
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Connection Error! The ModelControllerClient is not available.");
        }
        return null;
    }

**Comment by jamesnetherton** [comment]
This project is primarily concerned with Apache Camel integration with WildFly. So it'd be better if you contact the WildFly team directly:

https://issues.redhat.com/projects/WFLY/issues

https://stackoverflow.com/questions/tagged/wildfly

https://lists.jboss.org/mailman/listinfo/wildfly-dev

https://wildfly.zulipchat.com/
