### ISSUE TITLE
Migrate PR processing to GitHub Actions

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#3011]

**Comment by jamesnetherton** [comment]
This probably needs a whitelist (E.g configured as a GH secret) to verify the PR author against. Else, anyone can auto merge.

There are existing actions in the Marketplace that can do auto merging with whitelisting.

**Comment by tdiesler** [comment]
Is this really so? I found that the GITHUB_TOKEN associated with a PR from a fork (also mine and yours) will not have write access to target repo. A workaround, via Personal Access Token (PAT) that is available via secret and is then used by the checkout action (or by git commands) does also not work because secrets do generally not seem to be available for the pull_request event from a fork.

https://github.com/wildfly-extras/wildfly-camel/blob/master/.github/workflows/pr.yml#L43

This may change in the future, for now it means that we have to create our PR branches in the upstream repo if we want auto rebase+push. PRs from a fork will get processed by the workflow but won't get pushed.

**Comment by tdiesler** [comment]
Perhaps you'd like to have a second go at this. I have an experimental workflow that works on branch 'next' [here](https://github.com/wildfly-extras/wildfly-camel/blob/master/.github/workflows/workbench.yml). 

Try to do a git write when triggered by a pull_request from a fork. More generally, try to see secrets in the same case.
