### ISSUE TITLE
security constraints don't work in web.xml for undertow rest component

### ISSUE THREAD

**Issue by p4w3l** [wildfly-extras/wildfly-camel#3033]
created a project ( https://github.com/p4w3l/under ) that shows the problem where:

- web.xml definies security for whole WAR with
 `<url-pattern>/*</url-pattern>`
- and
 `<auth-constraint/>`
that should totally deny access to the webapp
and with simple *-camel-context.xml including
- restConfiguration with "undertow" component and simple rest for demonstration

in result you can : curl http://localhost:8080/camel/rest/say/ppp

when it should deny access!

WildFly 20.0.1 with Camel 12.0.0 from:
https://download.jboss.org/wildfly/20.0.1.Final/wildfly-20.0.1.Final.tar.gz
https://github.com/wildfly-extras/wildfly-camel/releases/download/12.0.0/wildfly-camel-patch-12.0.0.tar.gz

**Comment by jamesnetherton** [comment]
There's a bit of a configuration quirk in how Undertow endpoints created by Camel are secured. Try the following `url-pattern` in `web.xml` (note the three forward slashes):

```xml
<url-pattern>///*</url-pattern>
```

There's some wording on it buried in the [cxf docs](https://wildfly-extras.github.io/wildfly-camel/#_configuring_security_constraints_authentication_methods_and_security_roles). It probably needs adding to the undertow docs too.
