### ISSUE TITLE
Add CLI commands to enable scripting

### ISSUE THREAD

**Issue by geertschuring** [wildfly-extras/wildfly-camel#3046]
After searching for it I could not find any CLI commands to start or stop routes for instance. It would be great if we could control Camel entities through the CLI.

If I look in the Camel subsystem I see no Camel related commands:

```
[standalone@localhost:9992 /] cd subsystem=camel

[standalone@localhost:9992 subsystem=camel] ls
context
endpoints=["http://0.0.0.0:8080/hawtio","http://0.0.0.0:8080/<redacted>/v1"]

[standalone@localhost:9992 subsystem=camel] :
add                         map-get                     read-attribute-group-names  read-resource
list-add                    map-put                     read-children-names         read-resource-description
list-clear                  map-remove                  read-children-resources     remove
list-get                    query                       read-children-types         undefine-attribute
list-remove                 read-attribute              read-operation-description  whoami
map-clear                   read-attribute-group        read-operation-names        write-attribute
```

**Comment by tdiesler** [comment]
You can start/stop the deployment

**Comment by jamesnetherton** [comment]
There's also Jolokia / Hawtio, which can do these sorts of management operations.

**Comment by geertschuring** [comment]
> 
> 
> You can start/stop the deployment

I know, but I need more finegrained scripting options so I can start/stop individual routes.

**Comment by geertschuring** [comment]
> 
> 
> There's also Jolokia / Hawtio, which can do these sorts of management operations.

If you could explain how to start/stop a specific route using Jolokia that would be great!

**Comment by jamesnetherton** [comment]
> If you could explain how to start/stop a specific route using Jolokia that would be great!

With cURL & JSON it'd be something like this to stop a route:

```
curl http://localhost:8080/hawtio/jolokia/ \          
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '[{"type":"exec","mbean":"org.apache.camel:context=my-camel-context,type=routes,name=\"my-route\"","operation":"stop()","arguments":[]}]'
```

If your Jolokia endpoint requires authentication then you can do basic auth via the `-u` argument. E.g `-u my-username:my-password`.
