### ISSUE TITLE
wildfly launch.sh is not starting any of the ss7 services

### ISSUE THREAD

**Issue by joydeepb2** [wildfly-extras/wildfly-camel#3052]
I have followed the installation steps for jss7 in https://github.com/RestComm/jss7/wiki/Build-jSS7-from-Source.
Also followed the resolution for starting jss7 https://github.com/wildfly-extras/wildfly-camel/issues/1946

This is not working. 

It appears that binaries corresponding to the jss7 project is not getting copied to the wildfly home directory.

**Comment by jamesnetherton** [comment]
This is not the place to get general support for WildFly.

Please open an issue with the jss folks or the WildFly team.

https://github.com/RestComm/jss7/issues
https://issues.jboss.org/browse/WFLY
https://wildfly.zulipchat.com/
https://groups.google.com/forum/#!forum/wildfly
