### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by p4w3l** [wildfly-extras/wildfly-camel#3053]
Could you please elaborate a bit about future of Wildfly-Camel? Is the project abandoned because there is something else? Or simple lack of resources?

**Comment by tdiesler** [comment]
The RedHat integration team (Fuse) now focuses on cloud native tech with OpenShift, Quarkus, etc. Although the product side of this i.e. Enterprise Application Platform (FuseEAP) will be supported long time, the project side (i.e. this project) is unlikely to see much attention from the former team
