### ISSUE TITLE
standalone-camel.xml should not have a Camel context defined by default

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#313]
The sample Camel context within standalone-camel.xml should be removed. It sometimes gets confusing when writing tests etc and having a context showing up that wasn't explicitly required or wanted.

**Comment by tdiesler** [comment]
what specifically is the problem with that?

**Comment by jamesnetherton** [comment]
Why bootstrap and start something that you don't need?

**Comment by tdiesler** [comment]
ok. How about leaving it in but commented out?

**Comment by jamesnetherton** [comment]
Yes fair compromise :+1:

**Comment by jamesnetherton** [comment]
Wont fix. 

Having had a brief attempt at sorting out the consequences of removing the example context, I don't think this is worth the effort.

Any tests that rely on this context would need to add it programmatically on setup. This requires a server reload which Arquillian through JMX [seems unable to cope with](https://issues.jboss.org/browse/ARQ-791). The alternative is to have a specific standalone.xml file just for these tests. But, I don't want to add more server config files to the codebase without good reason, for maintenance purposes etc.

**Comment by tdiesler** [comment]
We already have standalone-camel-examples.xml for this purpose. The test suites could all use that.
