### ISSUE TITLE
Provide camel-soap integration

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#36]

**Comment by jamesnetherton** [comment]
If camel-soap refers to one of the publicly available Camel components - there is no such thing in existence. I think this is something [custom for Switchyard](https://github.com/jboss-switchyard/components/tree/b2563dca91aa619eda541b4a044b805c441ebc4a/soap/src/main/java/org/switchyard/component/soap).

**Comment by tdiesler** [comment]
won't fix
