### ISSUE TITLE
Route Diagram on Wildfly 8.2.0 throws RuntimeErrorException because of dumpRoutesAsXml

### ISSUE THREAD

**Issue by scsynergy** [wildfly-extras/wildfly-camel#375]
I was sent here to ask for help from this issue:
https://github.com/hawtio/hawtio/issues/1915
I doubt this is the right place for me to ask for help, since I do not use wildfly-camel but instead use:

```xml
        <dependency>
            <groupId>io.astefanutti.camel.cdi</groupId> (I read it is being actively integrated into apache camel since december to replace the existing camel-cdi)
            <artifactId>camel-cdi</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-sjms</artifactId>
            <version>2.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-mongodb</artifactId>
            <version>2.14.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>mongo-java-driver</artifactId>
                    <groupId>org.mongodb</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-core</artifactId>
            <version>2.14.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

and  hawtio-web-1.4.45.war.
But maybe somebody might be so kind to help me, anyway?

**Comment by tdiesler** [comment]
Using wildfly-camel instead of trying to provide your own integration layer has many benefits. We gladly help with making this use case work on top of wildfly-camel

**Comment by davsclaus** [comment]
@tdiesler I think widlfy has a general problem, what if people deploy .war files with a camel-core app. Then I suspect wildfly has that same problem reported here. That invoking dump routes as xml operation on the camel context mbean over JMX will fail. You can verify by just installing any camel .war app in widlfly, and connect using jconsole, and invoke that mbean operation.

**Comment by tdiesler** [comment]
The goal of this project is that wildfly/eap provides camel functionality out of the box. Replacing the provided camel (core) components with something else cannot be supported
