### ISSUE TITLE
Unable to use the wildfly-maven-plugin run goal to execute WildFly Camel examples  

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#380]
The purpose of the [examples](https://github.com/wildfly-extras/wildfly-camel/tree/master/examples) is to help folks get started with the WildFly Camel subsystem. Therefore, it makes sense that some of the examples are interactive and not just basic integration tests. 

At a minimum I'd expect a user to be able clone the project source, change into their desired example directory and deploy it to WildFly with `mvn wildfly:run`. 

The current Maven project structure in this area prohibits this and needs rethinking. Having sub modules depend on resources located higher up in the directory tree (I.e usage of ../ in paths) is a terrible practice IMO.

**Comment by tdiesler** [comment]
The current usage of the arq managed container bootstraps a wildfly instance as part of the BEFORE_SUITE event (i.e. one wildfly instance for all example module). This is true when all examples are run as part of a -Dts.all build.

At the same time, it is possible to navigate to an individual example module and run 'mvn clean install'. In this case all test cases in that example would run in the same container instance.

AFAIK, we don't create a dependency on resources higher up the maven tree. The dependency is on the distro artefact, which needs to be available in the local maven repo for examples to run
