### ISSUE TITLE
Add executable to enable/disable the camel subsytem

### ISSUE THREAD

**Issue by chirino** [wildfly-extras/wildfly-camel#563]
Example of a module that does something like that by applying xslt transforms can be found at:
https://github.com/dvirgiln/fuse-bxms-integ/tree/638baa0c44d6a02dbadd42cf0147b54e1b386377/release/eap/fuse-integration-eap-xslt

**Comment by tdiesler** [comment]
A feature like this would have to works consistently for all subsystems. Perhaps you like to take this to wildfly-dev for consideration

**Comment by tdiesler** [comment]
This needs a little more work:

* squash the commits and reference the issue (done already)
* remove hardcoded camel configs and use generated in tests
* replace hard coded exec-maven-plugin version with version property

**Comment by tdiesler** [comment]
Please don't forget, release date for this is Monday 01-Jun

**Comment by tdiesler** [comment]
To resolve this we associated documentation. We migration from decentxml to jdom can be deferred.

**Comment by tdiesler** [comment]
Deferred
