### ISSUE TITLE
Configure users/roles required by tests programmatically

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#626]
At the moment we have [these files](https://github.com/wildfly-extras/wildfly-camel/tree/master/examples/distro/etc/wildfly/standalone/configuration) to back up some of the integration tests that require user and user roles to be configured.

To enable the tests to be more portable, users / roles should be applied programmatically with  ServerSetupTask.

**Comment by tdiesler** [comment]
It turns out that setup tasks cannot be used reliably because they operate on a running server and it cannot be guaranteed that the tasks are executed before the security system reads its config. We go back to file copy from the POM.
