### ISSUE TITLE
Provide camel-linkedin support

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#673]
CrossRef: https://issues.jboss.org/browse/ENTESB-4604

**Comment by tdiesler** [comment]
Blocked by: https://issues.apache.org/jira/browse/CAMEL-8898

**Comment by tdiesler** [comment]
Blocked by camel-2.16

**Comment by tdiesler** [comment]
Blocked by https://issues.apache.org/jira/browse/CAMEL-9363

**Comment by dhirajsb** [comment]
Added instructions in https://issues.apache.org/jira/browse/CAMEL-9363 for running integration tests included in the component.

**Comment by tdiesler** [comment]
Here is the branch that started this https://github.com/tdiesler/wildfly-camel/tree/wfc673

**Comment by jamesnetherton** [comment]
Integration looks a bit messy so far....

* LinkedIn component depends on net.sourceforge.htmlunit:1.15 
* net.sourceforge.htmlunit:1.15 depends on org.apache.httpcomponents:httpclient:4.4.3 which is older and seemingly not fully compatible with WildFly's 4.5 version

An upgrade of htmlunit would pull in Jetty 9 which would likely conflict with the camel-salesforce component which requires Jetty 8.

So we either:

* Upgrade htmlunit and try to update camel-salesforce to use Jetty 9

Or

* Have a custom module in the fuse layer for httpcomponents under a 4.4.3 slot

**Comment by jamesnetherton** [comment]
This will probably solve some of the issues:

https://issues.jboss.org/browse/ENTESB-4877
