### ISSUE TITLE
Add support for extending set of wired modules

### ISSUE THREAD

**Issue by chirino** [wildfly-extras/wildfly-camel#680]
This would allow us to add the fuse integration package bits easier without having to resort to modifying fuse layer files.

**Comment by dvirgiln** [comment]
chirino if for wildfly-camel they want to create a subsystem, then my recommendation would be to reuse the code that is on
[18:17] <virchete> https://github.com/jboss-fuse/switchyard/tree/2.x.redhat-6-2-x-patch/release/jboss-as7/extension
[18:18] <virchete> include the common code on fuse-eap project and make switchyard and wildfly camel extend from that project
[18:18] <virchete> for not repeat code

**Comment by tdiesler** [comment]
What specifically is being asked here?

Adding a component that is not already part of the distribution requires one or more modules being added to the module hierarchy (i.e. adding stuff to the fuse layer). To make that module visible it can 

#1 be added to the components aggregation module
#2 referenced from a deployment descriptor 

The process is described [here](https://github.com/wildfly-extras/wildfly-camel-book/blob/master/components/README.md)

Generally, I believe that user added/modified components are not supportable. Therefore, component selection can only produce a subset of what we ship in a distribution.

**Comment by chirino** [comment]
The component we need to add is a camel-drools component that is part of Fuse integration pack.  I don't think encouraging users to modify the 'components aggregation module' is a good strategy since now the user is modifying the fuse layer and those changes could get easily overwritten if they 'reinstall' the fuse layer.

Forcing user to add a deployment descriptor to add the camel-drools component is not the user friendly either.  The SY subsystem supports configuring additional extension module in the subsystem config.  It makes sense if wildfly-camel could do the same.

**Comment by tdiesler** [comment]
If wfc deployments expect camel-drools to work, it must be a wfc supported component. IMO it does not make sense to use the wfc subsytem config as a bucket to add arbitrary modules to all wildfly deployments.

**Comment by tdiesler** [comment]
There is a requirement to support components at the product level that cannot be included in the project. It should for example be possible to add camel-drools in a product configuration without modifying files that may get overridden by patch content.

**Comment by tdiesler** [comment]
Done, we now support an optional module definition like this

```
<module xmlns="urn:jboss:module:1.1" name="org.wildfly.camel.extras">

    <dependencies>
        <module name="org.apache.camel.component.atom" export="true" services="export" />
    </dependencies>
    
</module>
```
