### ISSUE TITLE
Build stops, looking for httpclient

### ISSUE THREAD

**Issue by RickJWagner** [wildfly-extras/wildfly-camel#691]
The current build goes looking for http://maven.repository.redhat.com/techpreview/all/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar, but this jar is not to be found.  (The build hangs.)  
It looks like every jar in that vicinity has 'redhat' in it's name.
Thanks!

**Comment by jamesnetherton** [comment]
Hi,

I've tested running the build in a clean environment without any problems. The repository link that you mention does not feature in our build so maybe it's something in your `~/.m2/settings.xml` that's causing Maven to go looking for artifacts elsewhere.

What Maven version are you using? Also, when you refer to 'current build'. Is that the community or productized version of wildfly-camel?

**Comment by RickJWagner** [comment]
Hi James.  
Thanks for that response.  Your suspicion was correct, I removed a few extra entries from my settings.xml and cleaned my local repo, Wildfly-Camel built after that.
I'm working with the community build, BTW.  Trying to get a handle on the project, it's components and quickstarts, etc.
Thanks again.  This Issue can be marked 'closed'.
Rick
