### ISSUE TITLE
Unable to load camel type converters from package locations specified in TypeConverter manifest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#701]
To support Spring package scanning (see #366), we added a [custom PackageScanResolverClass](https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/src/main/java/org/wildfly/extension/camel/handler/PackageScanClassResolverAssociationHandler.java#L55). 

Camel loads type converters by looking at the META-INF/services/org/apache/camel/TypeConverter manifest within each component jar. Within this manifest you can list paths to concrete classes or specify the location to a package which contains type converter classes. 

The SAP component specifies a package location. This results in invocation of the custom PackageScanClassResolverImpl find() method. The problem is that it never sees the correct ClassLoader for the SAP component type converters. It only sees:
```
ModuleClassLoader for Module "org.apache.camel.core:main" 
ModuleClassLoader for Module "deployment.camel-sap-tests.war:main"
```
Where as the SAP type converters are located in:
```
ModuleClassLoader for Module "org.fusesource.camel.component.sap:main"
```

**Comment by tdiesler** [comment]
If a component module references some package it must either have direct access to that package (i.e. include the jar that contains the package) or declare a dependency on the module that contains the package.

In this example, I'd think  the SAP component should have a dependency on org.fusesource.camel.component.sap

**Comment by jamesnetherton** [comment]
The dependency wiring is correct so something else is preventing this from working.
