### ISSUE TITLE
Add support for security context propagation

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#725]
When a client successfully authenticated against a JavaEE endpoint (e.g. Servlet or EJB) it should be possible to call into a secured camel route without having to put authentication code in the JavaEE component.

Currently we have to do this

```
@Stateless
@DeclareRoles({ "Role1", "Role2", "Role3" })
@LocalBean
@SecurityDomain("other")
public class AnnotatedSLSB {

    @Resource(name = "java:jboss/camel/context/secured-context")
    CamelContext camelctx;

    @Resource EJBContext ejbctx;

    @RolesAllowed({ "Role1" })
    public String secureRouteAccess(String msg) {

        Subject subject = new Subject();
        String username = ejbctx.getCallerPrincipal().getName();
        Principal principal = new UsernamePasswordAuthentication(username, PASSWORD.toCharArray());
        subject.getPrincipals().add(principal);

        ProducerTemplate producer = camelctx.createProducerTemplate();
        return producer.requestBodyAndHeader("direct:start", msg, Exchange.AUTHENTICATION, subject, String.class);
    }
}
```

**Comment by darranl** [comment]
The existing WildFly APIs don't offer a mechanism to obtain the password, partly because this is a bad practice but also because depending on how authentication occurred we may not even have a password available to use.

For WildFly 10 we are working on the WildFly Elytron project to formally support both trusted invocations from server to server and delegated authentication where the remote user has provided us with a credential that can be delegated.

Any code built around an assumption that a plain text password is even likely to be available is unlikely to be supported in the future, at every opportunity we are trying to eliminate the use of plain text passwords anywhere.

Authentication schemes that support trusted delegation or schemes where invocations can be trusted to be executed on the behalf of another user are going to be the preferred option going forwards.

**Comment by tdiesler** [comment]
Yes, makes sense. In that case we'd could associate an authentication/authorization policy with route that verifies an existing trusted invocation. If this route also needs to be called directly, the policy probably needs to do both authentication/authorization and (if already available) verification of an already existing trusted invocation.

Is that about right?

**Comment by darranl** [comment]
That is the pattern we are taking for the invocations server to server, either we can make use of an already established identity or if none is available a new authentication can be performed.

**Comment by tdiesler** [comment]
What about within the same deployment? Does this pattern apply in that case too?

**Comment by darranl** [comment]
What we are working on within the application server is really around where the call crosses an authorization boundary - so same deployment that crossing should be unlikely as it should be using the same SecurityDomain so the same identity can be used.  Where the in-vm crossing is to a component with a different SecurityDomain then there is going to need to be a translation to the new domain.

**Comment by tdiesler** [comment]
Ok great. This will feature will have to wait for WildFly10, right?

**Comment by darranl** [comment]
For anything security related unless it is critical you have a solution now waiting for WildFly 10 would be advisable, we have something in the region of 8 engineers currently working to replace the security architecture of the server.

**Comment by tdiesler** [comment]
Hi @darranl, a year later I'd like to revisit this.

Is it now possible to obtain some sort of security context from within a EJB3 method and pass that on to a secured Camel route? 

In our code examples, we still have to pass in the credentials explicitly when calling into Camel. This should IMHO not be necessary because we are authenticated/authorized already. 

```
@Stateless
@DeclareRoles({ "Role1", "Role2", "Role3" })
@LocalBean
@SecurityDomain("user-domain")
public class AnnotatedSLSB {

    public static final String PASSWORD = "appl-pa$$wrd2";

    @Resource(name = "java:jboss/camel/context/secured-context")
    CamelContext camelctx;

    @Resource EJBContext ejbctx;

    @RolesAllowed({ "Role2" })
    public String secureRouteAccess(String msg) {

        // [TODO #725] Add support for security context propagation
        Subject subject = new Subject();
        String username = ejbctx.getCallerPrincipal().getName();
        subject.getPrincipals().add(new DomainPrincipal("user-domain"));
        subject.getPrincipals().add(new EncodedUsernamePasswordPrincipal(username, PASSWORD.toCharArray()));

        ProducerTemplate producer = camelctx.createProducerTemplate();
        return producer.requestBodyAndHeader("direct:start", msg, Exchange.AUTHENTICATION, subject, String.class);
    }
}
```

**Comment by tdiesler** [comment]
ok, merci.

**Comment by tdiesler** [comment]
Blocked by WildFly-11
