### ISSUE TITLE
How to access Context from EJB?

### ISSUE THREAD

**Issue by myfear** [wildfly-extras/wildfly-camel#744]
Hi,

I was wondering, if there is a way to access a @ContextName("cdi-context") from an EJB?
Injecting into a @Singleton @Startup doesn't work. I was trying to use EJB timer features to trigger a route.

Thanks for a hint.
M

**Comment by tdiesler** [comment]
We have various EJBs as injection targets for camel context, for example [this one](https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/standalone/extra/src/main/java/org/wildfly/camel/test/policy/subA/AnnotatedSLSB.java#L52)

```
@Stateless
@LocalBean
public class AnnotatedSLSB {

    @Resource(name = "java:jboss/camel/context/secured-context")
    CamelContext camelctx;
```

If this should indeed not work for your use case, you may want to verify that resource injection generally works (e.g. data source injection).

**Comment by myfear** [comment]
I did get it to work by just using @Inject CamelContext.
Which didn't work, was:
@Inject
@ContextName("cdi-context")
Private CamelContext camelctx;

The actual wildfly-camel/examples only contain the other way around. Accessing an EJB from a route. Thanks for the hint.
