### ISSUE TITLE
Verify that wildfly-camel runs on windows

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#750]
... in Jenkins

**Comment by tdiesler** [comment]
Won't Fix. We don't have a windows env to test this with for the project

**Comment by jamesnetherton** [comment]
Apart from the minor issue documented in #773. The build runs fine on Windows.

**Comment by myfear** [comment]
Can confirm. The only thing, that I ran across is an Arquillian issue. If someone initializes the JAVA_HOME environment variable with quotes (e.g. "d:\jdk18") the build fails. 
Just defining it without (e.g. d:\jdk18) works.
This implies that the JDK can't be in a path which contains special characters.

**Comment by jamesnetherton** [comment]
The logging issues are fixed. Everything now looks good :whale: - closing issue!
