### ISSUE TITLE
Investigate integration of container managed transactions within Camel routes

### ISSUE THREAD

**Issue by myfear** [wildfly-extras/wildfly-camel#754]
Dug around the samples and have to admit, that the
import org.springframework.transaction.jta.JtaTransactionManager;
doesn't look right ;) 
Isn't there a chance to do something like this:

```
@Inject
UserTransaction userTransaction;
jpaEndpoint.setTransactionManager(userTransaction);
```

**Comment by jamesnetherton** [comment]
I think we previously looked at avoiding having to use Spring in these scenarios.....

From what I remember, the Camel JPA Component (like JMS) expects a transaction manager of type `org.springframework.transaction.PlatformTransactionManager`. This is why we had to build a custom `JtaTransactionManager`  to wrap up the transaction managers that are pulled from the EE container.

Maybe this is something that could be looked at upstream in Camel. Although, I think the JMS component is completely coupled to spring, so this is probably not a trivial task to fix (assuming the same for JPA).

**Comment by jamesnetherton** [comment]
Indeed issue #267 talks about this in the context of the JMS component.

**Comment by jamesnetherton** [comment]
Using this thread to brain dump my thoughts.....

From what I've read from the [Camel documentation](https://camel.apache.org/transactional-client.html) and from the [code](https://github.com/apache/camel/blob/b378bcdedfbd0ac375d052ca4dccdbad6bed1ce9/camel-core/src/main/java/org/apache/camel/model/TransactedDefinition.java), most of the Camel transaction stuff is based around Spring.

You could probably write an application that makes use of standard JEE transaction idioms in beans, processors or EJBs. But, I see no way at the moment to support transactional camel routes without Spring. For example:
```
from("file:/bank/transactions")
.transacted()
.beanRef("accountService","credit")
.beanRef("accountService","debit");
```

Or transactions spanning multiple routes:

```
from("file:/bank/transactions")
.transacted()
.beanRef("accountService","credit")
   .choice().when(xpath("/transaction/transfer[amount > 100]"))
     .to("direct:txbig")
   .otherwise()
     .to("direct:txsmall");

from("direct:txbig")
.beanRef("accountService","debit")
.to("file:/bank/transactions/big");

from("direct:txsmall")
.beanRef("accountService","debit")
.to("file:/bank/transactions/small");
```

We should investigate to see if we can achieve this without using Spring.

**Comment by myfear** [comment]
+100
