### ISSUE TITLE
Starting Routes Leads To deltaspike Warning.

### ISSUE THREAD

**Issue by myfear** [wildfly-extras/wildfly-camel#764]
Any idea, where this comes from? 

> 2015-07-17 09:27:33,326 INFO  [org.apache.camel.cdi.CdiCamelContext] (MSC service thread 1-4) > Route: processCash started and consuming from: Endpoint[direct://processCash]
> 2015-07-17 09:27:33,326 WARNING [org.apache.deltaspike.core.api.provider.BeanManagerProvider] (MSC service thread 1-4) When using > the BeanManager to retrieve Beans before the Container is started, non-portable behaviour results!

**Comment by tdiesler** [comment]
Does not show any more with camel-2.16-SNAPSHOT
