### ISSUE TITLE
Endpoint creation on existing undertow server

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#779]
camel-undertow allows endpoint creation, it however requires that a new undertow server on a spare port gets started.

We can currently do this

```
        final int port = AvailablePortFinder.getNextAvailable(9080);
        final String httpurl = "http://localhost:" + port + "/myapp/myservice";

        CamelContext camelctx = new DefaultCamelContext();
        camelctx.addRoutes(new RouteBuilder() {
            @Override
            public void configure() throws Exception {
                from("undertow:" + httpurl).process(new Processor() {
                    @Override
                    public void process(Exchange exchange) throws Exception {
                        System.out.println("Processing: " + exchange);
                        Message in = exchange.getIn();
                        in.setBody("Hello " + in.getHeader("name"));
                    }
                }).to("seda:end");
            }
        });
```

It receives a HTTP request on an undertow endpoint on port 9080+ and passes that wrapped in an Exchange to the Processor that is associated with the endpoint.

I would somehow like to inject the existing undertow server on 8080 into the CamelContext and let the UndertowComponent reuse that server. Is that possible?

The UndertowComponent uses io.undertow.Undertown as server instance. Not sure what to do here because an instance of this type is not available in WildFly.

CrossRef: https://issues.apache.org/jira/browse/CAMEL-9033

**Comment by ctomc** [comment]
As long as you can access ServiceRegistry or any any of subsystem add handlers you can get / inject yourself a Undertow services that handle what you want.
main service that also has service names & static methods for getting service names for other parts you want to inject is:
org.wildfly.extension.undertow.UndertowService

from there one you probably want to get a Host service which handles the virtual hosts
so you could do 
ServiceName hostServiceName = UndertowService.virtualHostName("default-server", "default-host)

this will give you instance of org.wildfly.extension.undertow.Host 
which has methods like registerHandler(path, handler) which is probably want you want.

**Comment by tdiesler** [comment]
Blocked on camel-2.16
