### ISSUE TITLE
Unable to load custom Kafka Serializer or Partition classes 

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#819]
Attempting to use custom Kafka serializer or partition classes with 0.8.2.0 passes through this Scala code:

```scala
val klass = Class.forName(className).asInstanceOf[Class[T]]
```

This results in `org.apache.kafka:main` ModuleClassLoader being used. Custom classes wont be available to this module so we end up with a CNFE.

[KAFKA-2295](https://issues.apache.org/jira/browse/KAFKA-2295) is proposing to fix this in 0.9.0. The patch provided attempts to use the TCCL. This will probably work for WildFly but maybe they should allow clients to specify what CL should be used.

@tdiesler thoughts on this?

**Comment by jamesnetherton** [comment]
#775 is possibly related to this.

**Comment by tdiesler** [comment]
Blocked on camel-2.16

**Comment by tdiesler** [comment]
Can this go into 3.1.0?

**Comment by jamesnetherton** [comment]
Seems that this will be dependent on Camel consuming Kafka 0.9.0.0 or greater

**Comment by jamesnetherton** [comment]
Cross ref: https://issues.apache.org/jira/browse/KAFKA-2295

**Comment by jamesnetherton** [comment]
Kafka 0.9.0 is finally released:

https://issues.apache.org/jira/browse/CAMEL-9361

**Comment by tdiesler** [comment]
Done
