### ISSUE TITLE
Intermittent failures of JNDI Integration tests

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#825]
This error occurs occasionally: 
```
[0m[31m06:46:40,415 SEVERE [org.jboss.arquillian.protocol.jmx.JMXTestRunner] (pool-3-thread-1) Failed: org.wildfly.camel.test.jndi.JNDIIntegrationTest.testCamelContextFactoryLookup: org.jboss.msc.service.DuplicateServiceException: Service jboss.naming.context.java.helloBean is already registered
```

**Comment by jamesnetherton** [comment]
I can't reproduce this outside of the normal CI environment (even after running 100 builds). For some reason we seem to run into a situation where helloBean is not unbound from the JNDI context after the first test case (testArquillianResource) has completed. This then causes the following test to fail.

**Comment by jamesnetherton** [comment]
Closing for now. Can reopen if it becomes a problem.

**Comment by NKame** [comment]
It's a systematic error in certain cases when the route can't be loaded completely, for instance after a java.lang.IllegalArgumentException: Route echo-route has no outputs: Route(echo-route)[[From[direct://echo]] -> []]
        at org.apache.camel.model.RouteDefinitionHelper.sanityCheckRoute(RouteDefinitionHelper.java:353)
