### ISSUE TITLE
Add support for spring data access with jdbc

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#846]
See: [Data access with JDBC](http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/jdbc.html)

CrossRef: https://issues.jboss.org/browse/ENTESB-3953

**Comment by jamesnetherton** [comment]
I'm in two minds as to what we support for this.

Adding support for the Spring JDBC XML namespaces is fine. But, opening up all of Spring JDBC is potentially not a good idea. 

Once access to JDBC is open the next request will be for Spring transaction namespace support then for Spring AOP, etc, etc. We should be clear about drawing the line somewhere, ultimately we're targeting JEE as our platform and not Spring. Similarly, partial support for Spring features feels wrong. How do we define what is and is not supported?

If folks really want to develop on the full Spring stack, then the underlying modules are available. These could be included through manifest dependencies or deployment descriptors.

**Comment by jamesnetherton** [comment]
I think we should limit the scope of this task to adding support for the Spring JDBC namespace. Unless we come across specific use cases where folks need direct access to spring-jdbc, we should leave the majority of the API unexposed for now.
