### ISSUE TITLE
Add feature-pack dependency to archetypes module to ensure correct build order

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#853]
This is a result of the duff advice I gave on IRC (sorry Thomas!):

```
<tdiesler> jnetherton, is it true that archetypes have no deps on any other wfc module?
<jnetherton> tdiesler, yes correct
```

This is actually not the case. The archetype unit tests depend on the subsystem having been built and packaged beforehand.

Best to put this module back into it's previous place before the itest module.

**Comment by tdiesler** [comment]
A maven build cannot rely on the declared order in the POM, it must instead use dependencies to define the build order. A build that does not use dependencies break --also-make

IOW, this should work:

```
mvn clean install -pl archetypes -am
```
