### ISSUE TITLE
Allow automatic discovery/failover of the AMQ Broker

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#879]
The amq: endpoint works exactly like the activemq: endpoint in Apache Camel; only it uses the fabric to automatically discover the broker. So there is no configuration required; it'll just work out of the box and automatically discover whatever ActiveMQ message brokers are available; with failover and load balancing.

[http://fabric8.io/gitbook/camelEndpointAmq.html]

**Comment by jmesnil** [comment]
I'm not familiar with Camel and AMQ but there are some pointers that could help you:

An ActiveMQ Artemis JMS connection factory can be configured to either use a static list of servers to connect to or use a discovery mechanism to learn the cluster topology.
This is used to create an initial connection. Once this connection is established, the client is notified of any cluster changes (including failover/failback).

It looks like you would need to use org.hornetq.api.jms.HornetQJMSClient#createConnectionFactoryWithHA(org.hornetq.api.core.DiscoveryGroupConfiguration, org.hornetq.api.jms.JMSFactoryType) to create a JMS ConnectionFactory that discovers the cluster. The DiscoveryGroupConfiguration itself must match the JMS brokers configuration and can be backed by either JGroups or Artemis own UDP stack.

**Comment by tdiesler** [comment]
The [ActiveMQ component](http://camel.apache.org/activemq.html) should sufficiently cover this use case

```
        ConnectionFactory connectionFactory = createConnectionFactory();
        ActiveMQComponent activeMQComponent = new ActiveMQComponent();
        activeMQComponent.setConnectionFactory(connectionFactory);
        camelctx.addComponent("activemq", activeMQComponent);
```
