### ISSUE TITLE
Question: How can I see what version of camel is used in the docker image?

### ISSUE THREAD

**Issue by magick93** [wildfly-extras/wildfly-camel#900]
Hi

Actually - I have two questions:
1 - I see that Camel 2.16 is released, and the related issues here are closed. How can I check that the wildfly-camel docker image has been updated?
2 - For more discussion related topics or questions, is there are mailing list or forum? Or is it acceptable to post it as an issue in github?

**Comment by jamesnetherton** [comment]
For the docker image you can check the available tags on Docker Hub here:

https://hub.docker.com/r/wildflyext/wildfly-camel/tags/

We add a tag matching the wildfly-camel release (E.g 3.1.0) and the 'latest' tag always references the current wildfly-camel release.

As for discussions, feel free to raise an issue on GitHub or you can join us on IRC via Freenode at #wildfly-camel. Maybe it's worth getting a mailing list started for stuff like this. There's always the forums on http://www.jboss.org/forums/.

**Comment by magick93** [comment]
Thanks James.
+1 for the mailing list.
