### ISSUE TITLE
Error with swagger - RestModelConverters

### ISSUE THREAD

**Issue by magick93** [wildfly-extras/wildfly-camel#923]
Hi

I recently upgraded to Camel 2.16, and when I try to call the swagger documentation for my camel rest service in wildfly 9.1, I get the following error:

22:19:53,900 ERROR [io.undertow.request] (default task-29) UT005023: Exception handling request to /indicator-service/api-docs: java.lang.NoClassDefFoundError: Could not initialize class org.apache.camel.swagger.RestModelConverters

I am using latest stable of wildfly-camel. Wildfly 9.0.1 with Camel 2.16, with camel-swagger-java.

Any suggestions on how to fix this?

**Comment by jamesnetherton** [comment]
Can you share an example of how your camel route is configured?

**Comment by magick93** [comment]
Hi James, certainly:

```
@Override
	public void configure() throws Exception {
		restConfiguration().contextPath("/indicator-service/camel").port(8080).component("servlet")
				.bindingMode(RestBindingMode.json);

		rest("/indicator").description("IndicatorResource").produces(MediaType.APPLICATION_JSON)
				.consumes(MediaType.APPLICATION_JSON)

				.get("/{id}").description("Find an Indicator by Id").to("direct:indicatorFindById")

				.get("/").description("Find all Indicators").to("direct:indicatorFindAll")

				.delete("/{id}").description("Delete an Indicator").type(Indicator.class).to("direct:indicatorDelete")

				.post("/").description("Add an Indicator").type(Indicator.class).to("direct:indicatorSave")

				.post("/{id}/setting").description("Operation: createSetting, camel route: direct:indicatorCreateSetting")
				.type(IndicatorSettingDTO.class).to("direct:indicatorCreateSetting");

```

**Comment by jamesnetherton** [comment]
Here's the root cause:

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.PrettyPrinter from [Module "org.apache.camel.component.swagger:main" 
```

As a workaround you can add the following module dependency to `modules/system/layers/fuse/org/apache/camel/component/swagger/main/module.xml`

```xml
<module name="com.fasterxml.jackson.core.jackson-core" />
```

I tried disabling pretty printing but it still seems to want to load the `PrettyPrinter` class.

**Comment by jamesnetherton** [comment]
Here's the root cause:

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/PrettyPrinter
```

As a workaround you can add a module dependency to `modules/system/layers/fuse/org/apache/camel/component/swagger/main/module.xml` for:

```xml
<module name="com.fasterxml.jackson.core.jackson-core" />
```

**Comment by magick93** [comment]
Thanks James

Rather than doing a workaround, is it possible for me to do a PR for the wildfly-camel dockerfile?

**Comment by jamesnetherton** [comment]
Given that it's a minor thing, I just regenerated the Docker images with the fix, so no need for a PR.

Thanks for reporting the issue.
