### ISSUE TITLE
Add support for CDI apps without @ContextName

### ISSUE THREAD

**Issue by astefanutti** [wildfly-extras/wildfly-camel#925]
Given the current activation conditions, a CDI application is either required:
- To use the `@ContextName` annotation which is optional,
- To use the `@CamelAware` annotation which introduces a compile dependency on WildFly Camel.

A CDI application should be able to benefit from WildFly Camel without the two requirements above. A better activation condition should be defined for these applications.

**Comment by tdiesler** [comment]
This is currently controlled by the [CamelEnablementProcessor](https://github.com/wildfly-extras/wildfly-camel/blob/master/subsystem/src/main/java/org/wildfly/extension/camel/deployment/CamelEnablementProcessor.java#L47). Do you have a suggestion on how to improve this?

**Comment by jamesnetherton** [comment]
One possibility for this is to do something similar to camel-spring-boot, where any instances of `RoutesBuilder` classes found in the Spring bean factory are automatically added to a `SpringCamelContext`. All the user has to do is annotate their `RouteBuilder` with `@Component` or `@Bean`.

You could probably do something similar for CDI if you wanted to avoid `@ContextName`.

**Comment by astefanutti** [comment]
Indeed, that already works similarly in Camel CDI. Any `RoutesBuilder` beans is automatically instantiated and added to the corresponding Camel context at initialisation time.

So, if a bean archive contains any Camel abstractions like `RoutesBuilder`, `Component`, `Endpoint` or [Camel annotations](http://camel.apache.org/bean-integration.html#BeanIntegration-Annotations), it looks like a sensible choice to activate the Camel subsystem.

**Comment by tdiesler** [comment]
Is there really a scenario where we have a camel relevant CDI deployment, that does not use @ContextName? Is there really a scenario where a camel deployment uses Camel or Spring specific annotations and does not have a spring XML descriptor?

AFAIK, we cannot scan for implementations of a given interface.

**Comment by astefanutti** [comment]
If the end-user relies on the default Camel context bean deployed by Camel CDI and the default Camel context naming strategy, then the deployment won't contain any `@ContextName` annotation occurrence. This is the _getting started_ use case, so that'd be better not putting any constraint on the usage of the `@ContextName` annotation IMHO.

**Comment by tdiesler** [comment]
In that case, what is the discriminator that makes this a camel relevant deployment?

**Comment by astefanutti** [comment]
I'd said the original intent of the developer. In the Camel CDI example from Apache Camel (https://github.com/apache/camel/blob/master/examples/camel-example-cdi/src/main/java/org/apache/camel/example/cdi/MyRoutes.java#L28-L45), that intent is clear as he uses CDI annotations.

**Comment by tdiesler** [comment]
The other possible Camel CDI annotation is @Uri 

```
$ git grep "public @interface" | grep -v test
src/main/java/org/apache/camel/cdi/ContextName.java:public @interface ContextName {
src/main/java/org/apache/camel/cdi/Mock.java:public @interface Mock {
src/main/java/org/apache/camel/cdi/Uri.java:public @interface Uri {
```
We could add that in addition to @ContextName
