### ISSUE TITLE
Camel CDI module depends on DeltaSpike container control module

### ISSUE THREAD

**Issue by astefanutti** [wildfly-extras/wildfly-camel#926]
WildFly Camel declares a dependency on [DeltaSpike container control](https://deltaspike.apache.org/documentation/container-control.html) for the Camel CDI module in `modules/system/layers/fuse/org/apache/camel/component/cdi/main/module.xml`:
```
<module name="org.apache.deltaspike.cdictrl.api" />
```
DeltaSpike container control is used for bootstrapping the CDI container in Java SE and is redundant in the context of WildFly Camel.

Ideally, all the dependencies on DeltaSpike should be removed though the existing Camel CDI uses it. That will be solved once the improvement work on Camel CDI is available: https://github.com/astefanutti/camel-cdi. Then all the dependencies on DeltaSpike could be removed.

**Comment by tdiesler** [comment]
Do you have a Camel Jira we can cross reference from here?

**Comment by astefanutti** [comment]
@tdiesler that can be tracked by [CAMEL-9300](https://issues.apache.org/jira/browse/CAMEL-9300).

**Comment by jamesnetherton** [comment]
I see that the work for CAMEL-9300 is merged for Camel 2.16.1 & 2.17. 

Now that DeltaSpike is an optional dependency, We can remove it from our module defs and from the [CamelDependenciesProcessor DUP](https://github.com/wildfly-extras/wildfly-camel/blob/7a0eccaa2be3251a8abf5d0e8fa79026cdad1901/subsystem/src/main/java/org/wildfly/extension/camel/deployment/CamelDependenciesProcessor.java#L87-L94).

**Comment by astefanutti** [comment]
Note that `CAMEL-9300` only defines DeltaSpike container control as optional so that `<module name="org.apache.deltaspike.cdictrl.api" />` can be removed.

Other DeltaSpike dependencies will be completely removed when astefanutti/camel-cdi#7 will be merged in Camel.

**Comment by astefanutti** [comment]
[CAMEL-9201](https://issues.apache.org/jira/browse/CAMEL-9201) has been merged into master branch of Camel. The _blocked_ label may be removed.

**Comment by tdiesler** [comment]
out of date
