### ISSUE TITLE
Fuse patch support missing from wildfly-camel distribution

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#938]
We tell users that they can run fuseconfig.sh to enable the camel subsystem in their existing WildFly config files:

https://wildflyext.gitbooks.io/wildfly-camel/content/start/index.html

We can pull in the missing content from the fuse-patch distro bin directory.

**Comment by tdiesler** [comment]
I believe all of fuse-patch distro needs to be part of the wfc patch (for the project)

**Comment by jamesnetherton** [comment]
Does it though? We're only concerned with config file patching on the community branch.

The required WildFly modules are already part of the module tar.gz. All that's missing is the fuseconfig.sh script.

**Comment by tdiesler** [comment]
A model where foo contains bar is imho easier to maintain than a model where foo contains parts of bar. That we also add the patching functionality to the wfc distro does no harm.
